TileDB-Inc/TileDB-Py

README.rst
=> add that you need to put libtiledb on the ld path

README.rst
=> Update docs on Pip install

.travis.yml, README.rst, doc/source/python-api.rst, examples/quickstart_dense.py, examples/quickstart_kv.py, examples/quickstart_sparse.py, tiledb/__init__.py, tiledb/libtiledb.pyx
Also add three quickstart programs (and add to CI).
Doctests disabled on CI until I figure out how to get it to ignore whitespace differences.
=> Documentation work and misc small fixes.

.travis.yml, MANIFEST.in, doc/source/conda-env.yml, requirements.txt, requirements_dev.txt, setup.py, tiledb/libtiledb.pyx
- Add long_description with readme text
- Fix dependency specs in setup.py and requirements files
- Remove use of numpy 1.9 function np.full
- Intercept bdist_egg for native lib installation
- Fix RTD build failure.
=> Docs, installation and dependency fixes

examples/reading_dense_layouts.py, tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
add dense subarray read example
fix kv iter bug
Closes #13, #54
=> add subselection over attributes, allow coordinates for any layout

setup.py
if TileDB path is explicit or global TileDB is installed
also add wheel to install requires, closes #69
=> make cmake requires optional 

setup.py
=> Fix --tiledb arg; don't add cmake unnecessarily.

tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
Hat tip to @Shelnutt2 who pointed out this was missing. 
Closes #86
=> implement interator over attributes for ArraySchema

tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
=> add encryption support

tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
=> add key kw arg to array / kv consolidate

examples/fragments_consolidation.py, setup.py, tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
Update python api for new consolidation, removal of compressor api and other fixes/updates.
=> Update python api for latest dev changes

README.rst, examples/config.py, examples/errors.py, examples/fragments_consolidation.py, examples/kv.py, examples/multi_attribute.py, examples/object.py, examples/quickstart_dense.py, examples/quickstart_kv.py, examples/quickstart_sparse.py, examples/reading_dense_layouts.py, examples/reading_sparse_layouts.py, examples/using_tiledb_stats.py, examples/vfs.py, examples/writing_dense_multiple.py, examples/writing_dense_padding.py, examples/writing_sparse_multiple.py, tiledb/__init__.py, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
Also some minor KV API changes and fixes (KV.create returns an object)
Fixes #121
=> Make Ctx a keyword arg, with global default

.readthedocs.yml, doc/source/conda-env.yml
Trying to get RTD to pick up the branch so I can initiate a test build.
=> fix readthedocs

tiledb/highlevel.py, tiledb/libtiledb.pyx, tiledb/tests/test_dask.py, tiledb/tests/test_libtiledb.py, tiledb/tests/test_util.py
Plus some minor missing/unpushed fixes.
=>  Add docs for tiledb.save and tiledb.open

tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
Fixes #140 
Fixes several other indexing-related issues found or directly reported.
=> Fix several indexing issues

HISTORY.md, tiledb/libtiledb.pyx
(This starts from the release notes of 0.4.0)
=> Add HISTORY.md

tiledb/libtiledb.pyx
correctly propagate KeyboardInterrupt errors while cleaning up resources.
closes #39
=> wrap query_submits into try / finally blocks

.travis.yml, tiledb/highlevel.py, tiledb/tests/test_libtiledb.py, tiledb/tests/test_util.py
=> Add ctx to tiledb.open; implement tiledb.array_exists

tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
=> raise an error when trying to consolidate an open readonly array

tiledb/libtiledb.pyx
=> add some subarray examples to docstrings

setup.py
=> Suppress deprecation warnings

.travis.yml, azure-pipelines.yml, tiledb/libtiledb.pyx, tiledb/tests/test_examples.py
- Check all `examples/` via the unittests
- Doctest for pyx files still done on CI, add to azure config
- Fix windows doctest
=> Migrate doctests to azure config; add as unittest

azure-pipelines.yml, tiledb/tests/test_dask.py
This is a WIP. I will add tests as I develop code with Dask.
=> Add dask test for mapping blocks

tiledb/tests/test_domain_index.py
Added simple test to count number of points in a floating point domain.
=> Test counting by range with domain_index

tiledb/libtiledb.pyx, tiledb/tests/test_pandas_dataframe.py
=> whitespace, filename fixes

setup.py, tiledb/indexing.pxd, tiledb/indexing.pyx, tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/tests/test_domain_index.py, tiledb/tests/test_libtiledb.py
- support `domain_index[]` on DenseArray (in addition to Sparse)
- support `domain_index[]` on Query objects
=> domain_index updates

tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/np2buf.pyx, tiledb/tests/test_libtiledb.py
Opening PR to make sure this gets merged soon. (needs rebase, so I will update and merge in order)
=> WIP: Add support for TILEDB_DATETIME_* attributes, domains, and slicing.

tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
Fixes write path for non-string variable-length values to sparse arrays, and adds 2D test of that path for an integer attribute.
=> Fix non-string sparse varlen writes

tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
=> Fix varlen shape unpacking for single element access

tiledb/multirange_indexing.py, tiledb/tests/test_multi_index.py
=> Allow tuples as ranges in per-dim sub-selection

HISTORY.md, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
Also add round-trip test for `Attr.__repr__` added in #266.
=> Add __repr__ for ArraySchema

tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
(in addition to existing FilterList option)
Fixes #157
=> Add support for passing filters as Python list 

HISTORY.md, tiledb/dataframe_.py, tiledb/libtiledb.pyx, tiledb/tests/test_pandas_dataframe.py
=> Add support for read_csv taking input file from a TileDB VFS

tiledb/libtiledb.pxd, tiledb/libtiledb.pyx
x-ref https://github.com/TileDB-Inc/TileDB/pull/1528
=> Update for libtiledb 1.8 C API change [no backport]

misc/pypi_linux/build.sh
=> Add Python 3.8 wheel build step

setup.py
=> Print CMake output on failure

setup.py
=> Add error check for libtiledb build in setup.py

HISTORY.md, misc/azure-libtiledb-darwin.yml, misc/azure-release.yml
=> Update release CI with 0.5.7 fixes

HISTORY.md, examples/string_float_int_dimensions.py, tiledb/tests/test_libtiledb.py
- Update release notes for 0.6.0
- Add string+heterogeneous dimension example
- Add test for [ch1560]
=> Updates for release-0.6.0

tiledb/core.cc, tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/multirange_indexing.py, tiledb/tests/test_libtiledb.py
=> Fix offsets w/ incomplete, & implement unpacking in C++

tiledb/libtiledb.pyx, tiledb/multirange_indexing.py, tiledb/tests/test_libtiledb.py
- Fix regression when reading anonymous attributes (reported by bmccandless)
- Fix multi_index error with empty result for string attribute
=> More updates for 0.6.1

README.md
rendered: https://github.com/TileDB-Inc/TileDB-Py/blob/dde187d326287752916b6428a19a5389a12099ee/README.md
=> Fix link in README and add link to PyPI package

tiledb/dataframe_.py, tiledb/tests/test_pandas_dataframe.py
* Refactor/fix from_csv with sparse=True kwarg
* Add tests for from_csv:
- with index_col specified
- with `sparse=True` specified
[ch2423]
=> Fix from_csv(..., sparse=True), add more tests for from_csv

tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
=> Add schema support for allows_duplicates (for sparse array)

tiledb/dataframe_.py, tiledb/tests/test_pandas_dataframe.py
=> Support setting allows_duplicates with tiledb.from_csv

tiledb/dataframe_.py, tiledb/tests/test_pandas_dataframe.py
=> Support chunked CSV ingestion

tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
- adds repr for filters
- adds filters to ArraySchema repr
- adds 'capacity' to ArraySchema repr
- adds `__eq__` for `FilterList` and `Filter`
[ch2528]
=> Improve repr for ArraySchema, filters

tiledb/__init__.py, tiledb/dataframe_.py, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py, tiledb/tests/test_pandas_dataframe.py
- Fix and test from_csv with `sparse=False`, keyword was not plumbed through after sparse changes
- Fix and test repr for Attr w/ FilterList
- Validate from_csv mode argument
- Validate from_pandas mode argument and fix missing import
- Add missing from_pandas import in __init__
=> Fix and test from_csv with `sparse=False`; fix Attr repr w/ FilterList

tiledb/dataframe_.py, tiledb/libtiledb.pyx, tiledb/tests/test_pandas_dataframe.py
Related to https://github.com/TileDB-Inc/TileDB/issues/859
[ch2604]
=> Improve (sparse) tile default for dataframe ingestion

tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
=> Add tiledb.VFS.dir_size (wraps tiledb_vfs_dir_size)

tiledb/core.cc, tiledb/tests/test_core.py
- Fix bug in PyQuery::import_buffer (thanks @antalakas)
- Add test for Array._set_buffers with var-length attribute
=> Updates for PyQuery::import_buffer

HISTORY.md, misc/azure-release.yml, misc/pypi_linux/Dockerfile, misc/pypi_linux/Dockerfile2010, setup.py
=> Release 0.6.6: update HISTORY and bump libtiledb target to 2.0.7

README.md
=> Update README.md doc links

tiledb/libtiledb.pyx
* Array shows URI, mode, and ndim
* Ctx returns the same repr as Config
=> Add __repr__ For Ctx and Array

tiledb/libtiledb.pyx
Left over from previous coordinate system.
- (plus some docstring tweaks)
=> Allow indexing an attribute named 'coords'

examples/config.py, examples/errors.py, examples/fragments_consolidation.py, examples/multi_attribute.py, examples/multirange_indexing.py, examples/object.py, examples/parallel_csv_ingestion.py, examples/quickstart_dense.py, examples/quickstart_sparse.py, examples/reading_dense_layouts.py, examples/reading_sparse_layouts.py, examples/string_float_int_dimensions.py, examples/using_tiledb_stats.py, examples/variable_length.py, examples/vfs.py, examples/writing_dense_multiple.py, examples/writing_dense_padding.py, examples/writing_sparse_multiple.py
=> Update links and dates in examples

HISTORY.md, misc/azure-release.yml, misc/pypi_linux/build.sh, setup.py, tiledb/core.cc, tiledb/dataframe_.py, tiledb/libtiledb.pyx, tiledb/multirange_indexing.py, tiledb/tests/test_core.py, tiledb/tests/test_libtiledb.py, tiledb/tests/test_pandas_dataframe.py
Bump to TileDB Embedded 2.1.3, as well as additional fixes and improvements.
=> Updates for TileDB-Py 0.7.2

HISTORY.md, tiledb/dataframe_.py, tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py, tiledb/tests/test_pandas_dataframe.py
Allows to specify filters on a per-dim/attribute basis.
=> Support from_csv 'attr_filters' and 'dim_filters' as Dict[str -> FilterList]

tiledb/multirange_indexing.py, tiledb/tests/test_multi_index.py
Currently we need to set the ranges to the nonempty_domain in order to
avoid error in core.
=> Fix and test multi_index slice range indexing for dense arrays

tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
* Returns the unique dimension values for a given sparse array.
=> Addition of unique_dim_values() For SparseArrays

tiledb/multirange_indexing.py
In some use-cases, the array is not fully constructed so we don't know `nonempty_domain`, but in that case the ranges will always be fully-specified so we don't need to consider the `nonempty_domain` at all.
[ch4498]
=> Don't use nonempty_domain for multi_index fully-specified ranges

setup.py, tiledb/core.cc, tiledb/debug.cc, tiledb/fragment.cc, tiledb/libtiledb.pyx, tiledb/npbuffer.cc, tiledb/npbuffer.h, tiledb/tests/test_libtiledb.py, tiledb/tests/test_pandas_dataframe.py, tiledb/util.h
Benchmark converting 10,000,000 random strings (length=10)
Current implementation:
```
CPU times: user 10.6 s, sys: 184 ms, total: 10.8 s
Wall time: 11.1 s
```
This PR:
```
CPU times: user 267 ms, sys: 52 ms, total: 319 ms
Wall time: 326 ms
```
=> Optimize string array buffer conversion

tiledb/__init__.py, tiledb/core.cc, tiledb/multirange_indexing.py, tiledb/parquet_.py, tiledb/tests/test_libtiledb.py, tiledb/tests/test_pandas_dataframe.py
- Implement initial from_parquet functionality
- Update comment for async metadata preload section
- Update ArrowAdapter usage for TileDB Embedded 2.2.2
=> Updates for 0.8

setup.py
x-ref: https://github.com/conda-forge/tiledb-py-feedstock/pull/65/commits/6b8b406b105a0be3db94b80b78ba6cdb21b2597d
=> Cherry-pick 'Loosen NumPy pin' from conda feedstock

HISTORY.md, tiledb/multirange_indexing.py, tiledb/tests/test_multi_index.py
fix for https://github.com/TileDB-Inc/TileDB-Py/pull/473#issuecomment-784675012
=> Fix and test multi_index bug with sparse domain including zero

HISTORY.md, examples/writing_dense_rgb.py
=> Add RGB writing example

MANIFEST.in, README.md, examples/parallel_csv_ingestion.py, tiledb/dataframe_.py, tiledb/highlevel.py, tiledb/libtiledb.pyx, tiledb/tests/test_examples.py
=> Minor doc updates and compatibility cleanup

.github/workflows/format.yml, setup.py, tiledb/dataframe_.py, tiledb/npbuffer.h, tiledb/tests/test_examples.py, tiledb/util.h
* Ensure that Python files are formatted with the latest stable version of Black
* Ensure that C/C++ files are formatted with clang-format version 10
=> Add Lint GH Action

examples/fragment_info.py, tiledb/__init__.py, tiledb/fragment.py, tiledb/highlevel.py, tiledb/tests/test_fragment_info.py
* FragmentsInfo is an indexable and sliceable container class where each
object contains information about a single fragment
* array_fragments() is a high level function that returns a FragmentsInfo object
* The Pybind11 implementation of _fragment is no longer exposed the user
and array_fragments(uri) should be used instead of fragment_info(uri)
=> Addition of High Level array_fragments() Wrapper

tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
=> Remove deprecated 'np.object' usage

tiledb/tests/test_compat.py
Store a tgz of compatibility array like the other test.
The previous version only stored the schema file and overwrote it in place,
which is fiddly and doesn't work on core 2.3-dev after the attribute name changes.
=> Fix anonymous attribute backward compatibility test

tiledb/dataframe_.py, tiledb/tests/test_pandas_dataframe.py
- Add `attrs` and `use_arrow` optional parameters
- Reuse the `DataframeIndexer` code path
=> Extend tiledb.open_dataframe

tiledb/dataframe_.py, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
Fixes #445
---
closes [ch6165]
=> Support sparse write to dense array for ndarray indices

HISTORY.md, misc/azure-release.yml, tiledb/libtiledb.pyx
=> Update version to 0.8.7

misc/azure-libtiledb-darwin.yml, misc/azure-release.yml, misc/pypi_linux/Dockerfile2010
(simplifies testing changes on branches/forks)
=> Add libtiledb repository override for release build

examples/object.py, setup.py, tiledb/__init__.py, tiledb/array.py, tiledb/common.pxi, tiledb/libtiledb.pyx, tiledb/metadata.py, tiledb/tests/common.py, tiledb/tests/test_compat.py, tiledb/tests/test_core.py, tiledb/tests/test_examples.py, tiledb/tests/test_fragment_info.py, tiledb/tests/test_libtiledb.py, tiledb/tests/test_pandas_dataframe.py, tiledb/tests/test_util.py
Also sorted imports in the touched files with [isort](https://isort.readthedocs.io/en/latest/).
=> Clean up Python2 leftovers

tiledb/libmetadata.pyx, tiledb/tests/test_metadata.py
Adds support for writing and reading numpy arrays as metadata.
A numpy array is stored as one or two metadata values:
- The 1-D flat data values as returned by [numpy.ravel](https://numpy.org/doc/stable/reference/generated/numpy.ravel.html). The `dtype` is preserved for all numpy dtypes that have a corresponding TileDB type (e.g. `np.uint16 <-> TILEDB_UINT16`)
- The shape tuple, only if the original array is not 1-D. 
The keys for these values are prefixed by a fixed prefix to differentiate them from regular non-numpy keys:
- `_NP_DATA_PREFIX = "__np_flat_"`
- `_NP_SHAPE_PREFIX = "__np_shape_"`
- Get (`__getitem__`): First it looks up `key`; if it succeeds it returns it (non-numpy value), otherwise (numpy value) it does two extra lookups for `_NP_DATA_PREFIX + key` and `_NP_SHAPE_PREFIX + …
=> Numpy metadata

tiledb/highlevel.py
Mostly consolidation of the ctx/config logic for determining the final ctx. Also added a comment/question regarding the `save` vs `from_numpy` functions.
=> Refactor highlevel functions

tiledb/libtiledb.pyx, tiledb/tests/test_compat.py, tiledb/tests/test_libtiledb.py, tiledb/tests/test_metadata.py
=> Fix tests against libtiledb 2.3

tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
Small follow-up to #609 to increase coverage of the ArraySchema repr round-tripping.
=> Parametrize arrayschema repr test

misc/requirements_test.txt, setup.py
* Do not parse requirements.txt if building under conda-forge
=> Add install_requires() To setup.py

.github/workflows/ci.yml, .readthedocs.yml, tiledb/core.cc, tiledb/tests/test_fragment_info.py
(also enable --werror for github actions CI)
=> Fix readthedocs "latest" build

tiledb/tests/test_fragment_info.py
* Ensure that the fragment info version is within a reasonable bound
=> Relax `FragmentInfo` Version Checking

.github/ISSUE_TEMPLATE.md, .github/workflows/ci.yml, .github/workflows/daily-test-build.yml
See example of auto-created issue at https://github.com/nguyenv/TileDB-Py/issues/8
=> Create Issue on GitHub if Nightly Test Build Fails

tiledb/ctx.py
=> Print warning for ipykernel < 6 when using scope_ctx or default_ctx

HISTORY.md, tiledb/__init__.py, tiledb/ctx.py, tiledb/schema_evolution.py
=> Add wrapper class and docs for ArraySchemaEvolution

.github/workflows/ci.yml, .github/workflows/daily-test-build.yml, setup.py
* Fixes linker warnings for incompatible 10.15 vs 10.14
=> Fix Linker Warning macOS 10.14 vs 10.15

examples/parallel_csv_ingestion.py, tiledb/tests/common.py, tiledb/tests/test_multi_index.py, tiledb/tests/test_pandas_dataframe.py
Expanded testing for datetime indexes.
---
Needs fix for core issue ch 7192 (tbd)
=> Add improved sparse datetime index test

requirements.txt
=> Only Python Versions 3.10+ Require NumPy 1.21

HISTORY.md, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
* Modified to be more consistent with `dump_stats`
* Added argument `print_out` and `json`
=> Modify Function Signature of `Query` and `Ctx`'s `get_stats`

tiledb/core.cc
=> Add TILEDB_BLOB handling

tiledb/core.cc
Counterpart of https://github.com/TileDB-Inc/TileDB/pull/2770
Uses new query status information getter to control buffer resizing if the cause of an incomplete query was not insufficient user-provided memory.
=> Use tiledb_query_get_status_details to regulate buffer resizing

tiledb/core.cc, tiledb/multirange_indexing.py
Python side of https://github.com/TileDB-Inc/TileDB/pull/2738
=> Bulk range-set optimization

tiledb/core.cc
=> Loosen Restriction for `set_ranges_bulk` Function

tiledb/core.cc, tiledb/tests/test_pandas_dataframe.py
Fixes sc-13855. cc @aaronwolen
(needs test)
=> [merge before 0.12.2] Fix ArrowInvalid with nullable string attribute

setup.py, tiledb/tests/test_query_condition.py
* Tests strings greater than len(1)
* Tests both "ascii" `and np.bytes_`
=> Add `QueryCondtion` Unit Test `test_var_length_str`

tiledb/tests/test_fragments.py
=> xfail `test_delete_fragments_with_schema_evolution` until 3/16

.github/workflows/daily-test-build.yml, setup.py
* The CXXFLAGS were not being passed as the `remove()` call returns `None`
=> Correct CXXFLAGS For Installing `libtiledb`

tiledb/dataframe_.py
* Also remove deprecated `coords_filters`
=> Set `Zstdfilter` Default In `_get_schema_filters`

.github/workflows/daily-test-build.yml
The workflow is working correctly [here](https://github.com/TileDB-Inc/TileDB-Py/actions/runs/2173287234).
=> Also Run Nightly Builds On Current Release Branch

HISTORY.md, tiledb/filter.py, tiledb/libtiledb.pyx, tiledb/tests/test_fragments.py, tiledb/tests/test_libtiledb.py
[sc-16969]
[sc-16170]
[sc-13614]
=> Refactor HTML Repr And Add Testing

setup.py, tiledb/tests/test_pandas_dataframe.py
* Fixed by https://github.com/TileDB-Inc/TileDB/pull/3161
=> Add `test_append_empty_dataframe`

setup.py, tiledb/cc/common.cc, tiledb/core.cc, tiledb/libtiledb.pyx, tiledb/np2buf.pyx, tiledb/py_arrow_io_impl.h, tiledb/tests/test_libtiledb.py
In `setup.py`, read the `TILEDB_VERSION_*` macros from `tiledb/tiledb_version.h` and pass them to Cython.
=> Check `libtiledb`>=2.10 for `TILEDB_BOOL`

HISTORY.md, tiledb/cc/object.cc, tiledb/group.py, tiledb/object.py, tiledb/tests/test_group.py
* If the name is not given, returns None
=> `Group.member` Also Returns `name` If Given

HISTORY.md, tiledb/query_condition.cc, tiledb/query_condition.py, tiledb/tests/test_query_condition.py
=> Support OR Query Condition

tiledb/tests/test_multi_index-hp.py
These were implicitly matched via defaults until changes in https://github.com/TileDB-Inc/TileDB/pull/3207
Also add parametrization so we try the hypothesis test on row, col, and global order queries.
=> Use matching query order for the two_way_query test. Fixes SC-18696

tiledb/tests/test_pandas_dataframe.py
* See https://github.com/TileDB-Inc/TileDB-Py/issues/1306#issuecomment-1233570928
=> Add `na_filter=False` To `from_csv` in `test_tile_and_cell_order`

HISTORY.md, tiledb/highlevel.py, tiledb/tests/test_util.py
=> Add ability to pass shape tuple to empty_like 

misc/requirements_wheel.txt, requirements_dev.txt
The issue was fixed upstream in `https://github.com/pypa/setuptools/issues/3196`.
x-ref https://github.com/TileDB-Inc/TileDB-Py/pull/995#issuecomment-1237765097
=> Remove setuptools pinning

HISTORY.md, misc/azure-release.yml, setup.py
=> Release 0.17.3 Against libtiledb 2.11.2

tiledb/filter.py, tiledb/tests/test_filters.py
=> Add parametrization on filter type; test and fix filter_list __repr__

tiledb/core.cc
Findings from debug on https://github.com/TileDB-Inc/TileDB/pull/3620
=> Resizing issues

tiledb/tests/test_libtiledb.py
=> Remove xfail from simple3d_sparse_vector

tiledb/filter.py
=> Comment-neaten for for FloatScaleFilter

tiledb/attribute.py, tiledb/cc/context.cc, tiledb/cc/filter.cc, tiledb/core.cc, tiledb/ctx.py, tiledb/filter.py
- Also modify the `PyQuery` constructor to take a `Context` directly instead of `py::object`
=> Refactor `Attr` and `FilterList` To Use Copy Constructor

tiledb/filestore.py
Add note about filestore array/schema creation
=> Add note about filestore array/schema creation

tiledb/libtiledb.pyx
Clean-up the internal helper method for writing arrays.
=> Refactor _write_array

tiledb/filter.py
Updates WebP documentation surrounding accepted datatypes for dimensions and attributes. Follow-up for TileDB-Inc/TileDB#3752.
=> Update WebP documentation

tiledb/filter.py
Also refactor `FilterList._getfilter` and rename to `_filter` while at it.
=> Update FilterList to take into account WebpFilter options

tiledb/libtiledb.pyx, tiledb/tests/common.py, tiledb/tests/test_libtiledb.py, tiledb/tests/test_stats.py
=> Update stats test for 2.15, fix SC-24954

tiledb/array_schema.py, tiledb/dimension_label.py, tiledb/dimension_label_schema.py, tiledb/libtiledb.pyx
Add or update `CtxMixin` support to the the recently merged https://github.com/TileDB-Inc/TileDB-Py/pull/1340 and  https://github.com/TileDB-Inc/TileDB-Py/pull/1397.
=> CtxMixin for ArraySchema and dimension labels

examples/config.py, tiledb/tests/cc/test_group.py, tiledb/tests/test_context_and_config.py
Fixes #1625 #1626 #1627 #1628 #1629 #1631 #1632 #1634 #1635 #1636 #1637 #1638
=> Fix SC-25186: updates for 2.15-dev changes

.github/workflows/daily-test-build.yml
=> Also install pkg-config in nightly CI script

examples/quickstart_dimension_labels.py, tiledb/__init__.py, tiledb/cc/dimension_label.cc, tiledb/cc/query.cc, tiledb/cc/subarray.cc, tiledb/core.cc, tiledb/dimension_label.py, tiledb/libtiledb.pyx, tiledb/multirange_indexing.py, tiledb/query.py, tiledb/subarray.py, tiledb/tests/test_dimension_label.py, tiledb/tests/test_query.py, tiledb/tests/test_subarray.py
Adds support for querying a dense array by dimension label.
=> Query dense array by dimension label

.github/workflows/daily-test-build-numpy.yml, .github/workflows/daily-test-build.yml
Also install pkg-config in the oldest-numpy nightlies.
fixes #1669
fixes #1670 
fixes #1671
=> Add release-2.15 to nightly tests

tiledb/tests/cc/test_cc.py, tiledb/tests/test_fixes.py
=> Update Array.set_config test

.github/workflows/ci.yml, tiledb/vfs.py
Fix sc-30787, VFS S3 write failure due to un-closed handle
=> Fix sc-30787, VFS S3 write failure

.github/workflows/ci.yml
https://github.com/TileDB-Inc/TileDB-Py/pull/1798#issuecomment-1607612327
=> Correct Syntax Errors in `ci.yaml`

tiledb/tests/test_basic_import.py
Because the tiledb-cloud package necessarily has to import Pandas if the installed version of Pandas is old, we also need to suppress the importing of tiledb.cloud in the Pandas import test if the version of Pandas available is old. (This specifically happens in py3.7.)
=> Ensure that the Pandas import test will work with old Pandas.

.github/workflows/daily-test-build-numpy.yml
Fixes #1817
Successful test run: https://github.com/TileDB-Inc/TileDB-Py/actions/runs/6207746278
=> Update nightly build setup

.github/workflows/format.yml, ci/scripts/check_formatting_linux.sh, ci/scripts/install-clangformat.sh, ci/scripts/run-clang-format.sh, doc/requirements_doc.txt, doc/source/conf.py, misc/requirements_ci.txt, tiledb/cc/array.cc, tiledb/cc/filter.cc, tiledb/cc/schema.cc, tiledb/core.cc, tiledb/fragment.cc, tiledb/npbuffer.cc, tiledb/query_condition.cc, tiledb/serialization.cc, tiledb/tests/test_metadata.cc, tiledb/tests/test_serialization.cc
Update clang-format to version 16.
=> Update clang-format to version 16

examples/quickstart_dimension_labels_sparse.py
Add an example of how to use dimension labels on sparse data.
=> Add sparse dimension label example

misc/azure-release.yml
=> Release 0.23.3 With Enumeration Bug Fix

tiledb/cc/enum.cc, tiledb/cc/filter.cc, tiledb/filter.py, tiledb/tests/test_filters.py
- Add enum value to FilterOption
- Add as an option for DeltaFilter and DoubleDeltaFilter
=> Add COMPRESSION_REINTERPRET_DATATYPE to allowed FilterOption

.github/workflows/daily-test-build-numpy.yml, setup.py
Fix versions for setup.py and daily-numpy. Closes https://github.com/TileDB-Inc/TileDB-Py/issues/1898
=> Fix versions for setup.py and daily-numpy

.github/workflows/issue-if-azure-fail.yml
Add KiterLuc,kounelisagis to nightly issue notification
=> Add KiterLuc,kounelisagis to nightly issue notification

tiledb/group.py, tiledb/tests/test_fixes.py
=> Remove erroneous _ctx check for GroupMetadata

tiledb/libtiledb.pyx
Fix docstring for `upgrade_version`
=> Fix docstring for `upgrade_version`

HISTORY.md, misc/azure-release.yml, setup.py, tiledb/tests/test_query_condition.py
[sc-43172]
Update HISTORY for 0.27.0 against TileDB 2.21
=> Update HISTORY for 0.27.0 against TileDB 2.21

HISTORY.md, misc/azure-release.yml, setup.py
Update HISTORY for 0.27.1 against TileDB 2.21.1
=> Update HISTORY for 0.27.1 against TileDB 2.21.1

.github/workflows/daily-test-build-numpy.yml, .github/workflows/daily-test-build.yml
Add Agis and Luc to daily test notification list.
=> Add Agis and Luc to daily test notification list

tiledb/enumeration.py, tiledb/tests/test_enumeration.py
=> Show enumerated value-types in enum-printer

tiledb/highlevel.py
List all the keyword arguments for `from_numpy` function.
=> Improve documentation of from_numpy function

tiledb/cc/array.cc, tiledb/cc/common.cc, tiledb/cc/dimension_label.cc, tiledb/cc/enum.cc, tiledb/cc/group.cc, tiledb/cc/schema.cc, tiledb/cc/subarray.cc, tiledb/core.cc, tiledb/fragment.cc, tiledb/py_arrow_io_impl.h, tiledb/query_condition.cc, tiledb/serialization.cc, tiledb/tests/test_metadata.cc, tiledb/tests/test_serialization.cc
Remove conditional code for TileDB < 2.16
=> Remove conditional code for TileDB < 2.16

.github/workflows/daily-tests.yml
Update nightly test target to 2.21
=> Update nightly test target to 2.21

setup.py, tiledb/cc/array.cc, tiledb/tests/cc/test_cc.py
=> Wrap tiledb_array_consolidate_fragments from pybind11

HISTORY.md, misc/azure-release.yml, setup.py
Update HISTORY for TileDB-Py 0.24.1 against TileDB 2.18.5
=> Update HISTORY for TileDB-Py 0.24.1 against TileDB 2.18.5

.github/workflows/daily-tests.yml
Update daily-tests.yml to add release-2.22
=> Update daily-tests.yml to add release-2.22

HISTORY.md, misc/azure-release.yml
Update HISTORY and version for 0.29.1
=> Update HISTORY and version for 0.29.1

.github/workflows/daily-tests.yml
Update daily-tests.yml to add release-2.24
=> Update daily-tests.yml to add release-2.24

CMakeLists.txt, setup.py
- REQUIRE -> REQUIRED typo
- support finding TileDBConfig in subdirectory (like previous setup.py)
=> Add setup.py fallback for install and develop, and fix some CMake issues

CMakeLists.txt, doc/source/python-api.rst, tiledb/__init__.py, tiledb/array_schema.py, tiledb/cc/CMakeLists.txt, tiledb/cc/current_domain.cc, tiledb/cc/enum.cc, tiledb/cc/schema.cc, tiledb/cc/tiledbcpp.cc, tiledb/current_domain.py, tiledb/ndrectangle.py, tiledb/schema_evolution.cc, tiledb/schema_evolution.py, tiledb/tests/test_current_domain.py
Wrapping https://github.com/TileDB-Inc/TileDB/pull/5056
=> Wrap current domain API

tiledb/core.cc, tiledb/libmetadata.pyx, tiledb/metadata.py
=> Move `PackedBuffer` and `pack_metadata_val` to pure Python, and wrap `tiledb_datatype_size` with pybind

.github/workflows/daily-test-build-numpy.yml, .github/workflows/daily-test-build.yml, HISTORY.md, README.md, tiledb/cc/context.cc, tiledb/tests/test_vfs.py
This PR addresses several general issues.
=> General fixes

tiledb/tests/test_libtiledb.py
Historically, we had several tests that overrode the timestamp for writes to avoid test failures when multiple writes occurred within the same millisecond. By leveraging https://github.com/TileDB-Inc/TileDB/pull/4800, we modified these tests in https://github.com/TileDB-Inc/TileDB-Py/pull/1953 to run both with and without these overrides.
`DenseArrayTest::test_open_with_timestamp[False]` has frequently failed, locally, on the [TileDB-Py CI](https://github.com/TileDB-Inc/TileDB-Py/actions/runs/11321329322/job/31480234054#step:12:1016), and the [centralized-tiledb-nightlies](https://github.com/TileDB-Inc/centralized-tiledb-nightlies/issues/24#issuecomment-2389422080).
It turns out that the logic of this test was not entirely correct. The test writes three fragments, one after another, and …
=> Fix randomly failing test `DenseArrayTest::test_open_with_timestamp[False]`

tiledb/tests/test_group.py
Should fix https://github.com/TileDB-Inc/TileDB-Py/actions/runs/11587357551
Triggered daily tests workflow: https://github.com/TileDB-Inc/TileDB-Py/actions/runs/11591425398
=> Change `np.bool` to `np.bool_` - Daily Tests fix

doc/source/python-api.rst
=> Add missing filters to docs

tiledb/dense_array.py, tiledb/sparse_array.py, tiledb/tests/test_query_condition.py
=> Add specific error messages based on the mode the Array is opened

tiledb/__init__.py
=> Add `cc` alias for `libtiledb`

HISTORY.md
Update HISTORY for 0.34.2 against TileDB 2.28.1
Closes CORE-339
=> Update HISTORY for 0.34.2 against TileDB 2.28.1
