.gitignore, .travis.yml, MANIFEST.in, README.rst, requirements_dev.txt, setup.py, tiledb/__init__.py
The native library is installed with the wheel (as "package data") if setup.py downloads and builds libtiledb.
=> Rework setup process to download/install TileDB if necessary.

.travis.yml, requirements.txt, setup.py
with custom tiledb install directory
switch to strict lower bound for requirements.txt
=> Search over lib${ARCH} and libmultiarch paths when building extension

setup.py
- as discussed, change target to TileDB stable while working on CI improvements.
- fix build on macOS 10.14, where libstdc++ is no longer available. The deployment target needs to be set in order to properly use libc++ (see `https://github.com/pandas-dev/pandas/pull/24274`)
=> Fix macOS 10.14 build

azure-pipelines.yml, requirements_dev.txt, setup.py, tiledb/__init__.py, tiledb/tests/test_libtiledb.py
includes and closes #97 
fixes #98
=> CI for mac and win (WIP) on Azure pipelines

tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
- add `FilterList::append`
- bug fix: FilterList(filters) constructor kwarg was not actually optional (tried to iterate over `None` -> error)
=> FilterList.append and bug-fix

tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
Output of reading the var length C++ example output array:
```
import tiledb
ctx = tiledb.Ctx()
uri = "/Users/inorton/work/scratch/varlen_scratch-20190214/varlen.cc/variable_length_array"
v1 = tiledb.DenseArray(ctx, uri)
print(v1[1:5 , 1:5])
```
```
OrderedDict([('a1', array([[b'a', b'bb', b'ccc', b'dd'],
[b'eee', b'f', b'g', b'hhh'],
[b'i', b'jjj', b'kk', b'l'],
[b'm', b'n', b'oo', b'p']], dtype=object)), ('a2', array([[array([1, 1], dtype=int32), array([2, 2], dtype=int32),
array([3], dtype=int32), array([4], dtype=int32)],
[array([5], dtype=int32), array([6, 6], dtype=int32),
array([7, 7], dtype=int32), array([8, 8, 8], dtype=int32)],
[array([9, 9], dtype=int32), array([10], dtype=int32),
array([11], dtype=int32), array([12, 12], dtype=int32)],
[array([13], dtype=int32), array([14, 14, …
```
=> varlen array support

setup.py, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
This PR adds a lower-level "ReadQuery" class, which executes a query and stores the result as simple numpy byte buffers. The dense and sparse array subclasses are refactored to use this class, which consolidates `tiledb_*` read logic in one place, and simplifies the implementation. (also useful for integration prototyping and debugging)
=> Add ReadQuery class (query->buffer), and refactor both array classes to use

README.rst
`wget https://github.com/TileDB-Inc/TileDB-Py/blob/dev/examples/quickstart_dense.py' pulls
the rich github web page. We should update this to the raw file URL:
https://raw.githubusercontent.com/TileDB-Inc/TileDB-Py/dev/examples/quickstart_dense.py
=> Update quickstart_dense.py URL in README

doc/source/conda-env.yml, doc/source/conf.py, setup.py, tiledb/libtiledb.pyx
- fixes building against out-of-source libtiledb on newer macOS: previously the deployment target override only applied when building libtiledb from source w/in setup.py, but the cython build also needs this setting.
- minor doc fixes/clean-ups
=> Mac10.14 out-of-source fix and minor docs clean-up

misc/pypi_linux/Dockerfile, misc/pypi_linux/build.sh, setup.py, tiledb/__init__.py
Adds Dockerfile and associated build script to create manylinux1
wheels for TileDB-Py targeting py27 and py37
- introduce Dockerfile inheriting from manylinux1
- improve build system support for linux wheel packaging
(also includes a fix to allow overriding the cmake binary, which should help to fix doc builds on RTD)
=>  Add Dockerfile to make manylinux1 wheels (e.g. for PyPI)

azure-pipelines.yml, tiledb/__init__.py, tiledb/highlevel.py, tiledb/libtiledb.pyx, tiledb/tests/common.py, tiledb/tests/test_dask.py, tiledb/tests/test_libtiledb.py, tiledb/tests/test_util.py
This PR contains
- rework DenseArray to support single-attribute view on a multi-attribute array
- set  of API additions, motivated by dask support (but hopefully generally useful):
- convenience functions:
- `open`, `save`
- aliased `from_numpy` to allow use as simply `tiledb.from_numpy`
- util functions to make schema and array from numpy-style specifiers (rather than spelling out `Dim`,`Domain`)
- `schema_like`: create ArraySchema based on a numpy ndarray template, or numpy-style `shape` and `dtype` kwargs
- `empty_like`: returns a writable, emtpy array similar to an existing ndarray-like object (`.dtype`, `.shape`).
- basic CI for dask integration to make sure we don't break that here, going forward
=> HL API additions for dask

.travis.yml, examples/multi_attribute.py, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
Added support and tests for numpy complex data types.
There is an assumption that array sizes that are equal to two and are of type float 32/64 are to be interpreted as complex data types. This seems reasonable and follows numpy.
=> Added support for numpy complex types

azure-pipelines.yml, requirements.txt, requirements_dev.txt, setup.py, tiledb/libtiledb.pyx, tiledb/tests/common.py, tiledb/tests/test_libtiledb.py
`PyArray_NewFromDescr` ignores the `NPY_ARRAY_OWNDATA` flag, so we
need to set it manually so that NumPy frees the memory.
Fixes #150
=> Fix memory leak

tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
=> allow Array.create() to take an optional ctx to override schema

misc/pypi_linux/Dockerfile, misc/pypi_linux/build.sh, setup.py
- AWS SDK and TileDB core have a number of default constructors which cause
'unused parameter' warnings under GCC 4.8. I have manually run unit tests
against Minio with a GCC 4.8 build, and all tests passed.
- ~~disable ~~HDFS and CPP_API, which don't make sense to build for the wheel.~~
=> Fix PyPI wheel build for TileDB 1.6

setup.py
This fails under the combination of conda-build/distutils/cython on the tiledb-py-feedstock CI builder. Not clear why it works correctly on CI here and locally, but fix here so conda doesn't need a work-around in the next release.
=> Don't set runtime_library_dirs on Windows

tiledb/libtiledb.pyx, tiledb/test_pandas_dataframe.py, tiledb/tests/test_libtiledb.py
Adds, and fixes, a test for round-tripping a multi-attribute array to/from a Pandas dataframe.
Based on @tdenniston internal bug report.
=> Fix var-length writing bug and add dataframe conversion test reproduction

examples/variable_length.py, tiledb/libtiledb.pyx, tiledb/tests/common.py, tiledb/tests/test_libtiledb.py
- adds `variable_length.py` example (port of C++ example)
- adds test and fix for multi-dimensional var-len subarray assignment
- adds simple test helper for comparing var-len subarrays
=> Add variable_length example; adds var-len subarray assignment test and fix

.travis.yml, azure-pipelines.yml, examples/errors.py, examples/object.py, examples/variable_length.py, examples/vfs.py, requirements.txt, requirements_dev.txt, setup.py, tiledb/__init__.py, tiledb/common.pxi, tiledb/indexing.pxd, tiledb/indexing.pyx, tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/np2buf.pyx, tiledb/tests/test_domain_index.py, tiledb/tests/test_examples.py, tiledb/tests/test_libtiledb.py
Add `Array.domain_index` operator, which supports slicing over any range within the domain bounds, including negative slices (previously limited for the Array[] operator by NumPy wrap-around semantics). Slice ranges are passed down to libtiledb core for range and point queries.
Fixes #102
Fixes #201
=> Add `domain_index` operator

misc/pypi_linux/Dockerfile
This also bumps libtiledb to 1.6.3 for manylinux.
This separates the enabling of serialization in wheels vs the default for source building.
=> Enable serialization in manylinux wheels

tiledb/common.pxi, tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
Add support for retrieving fragment information (URI, timestamp range) for the most recent write operation on a given `Array` object, via the `Array:last_write_info` method.
---
depends on https://github.com/TileDB-Inc/TileDB/pull/1396
=> Wrap new fragment info API functions

azure-pipelines.yml
Azure pipelines python, activated via `UsePythonVersion@0`, in the `macOS-10.13` image seems to have been broken in an update. Details in https://github.com/microsoft/azure-pipelines-image-generation/issues/1342
This PR switches to the `macOS-10.14` image, which requires setting `SDKROOT` in the environment in order for TBB (via CMake) and probably other build targets to find things like `stdlib.h`.
=> Fix mac CI: switch to macOS-10.14 image and set SDKROOT

tiledb/libtiledb.pxd, tiledb/libtiledb.pyx
Requires latest TileDB dev / TileDB 1.7
=> Bind ctx_set_tag API; set default tags in Ctx init.

tiledb/__init__.py, tiledb/array.py, tiledb/indexing.pyx, tiledb/libtiledb.pxd, tiledb/libtiledb.pyx
Adds support for mix-in functionality defined in tiledb.cloud when
installed.
Co-authored-by: Seth Shelnutt <seth@tiledb.io>
=> Define Dense and Sparse Array in pure python

tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
We already have a top-level `ls()`, but it seems useful to have this call on the VFS class, which maps to `tiledb_vfs_ls`.
=> Add ls() method to VFS class

tiledb/indexing.pyx, tiledb/tests/test_multi_index.py
=> Fix bug in multi_index result buffer calculation

tiledb/common.pxi, tiledb/highlevel.py, tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/multirange_indexing.py, tiledb/tests/test_examples.py
Adds a factory-like static method, `Array.load_typed`, which returns
a DenseArray or SparseArray instance, depending on the type of the
underlying array. Eliminates the current schema check before class
allocation, which adds latency in non-local usage.
=> Add tiledb.Array.load_typed for typed open w/out separate schema check

tiledb/array.py
Importing is not thread-safe in several recent python releases:
https://bugs.python.org/issue38884
Fixes #244
=> Set cls._mixin_init before import, fix import race

tiledb/indexing.pxd, tiledb/indexing.pyx, tiledb/libtiledb.pxd, tiledb/metadata.pyx, tiledb/multirange_indexing.py, tiledb/tests/test_libtiledb.py
In #247 @bkmartinjr demonstrated thread-count oversubscription caused by delayed Array destruction (thus, Ctx deallocation), due to internal reference cycles. These cycles can eventually be freed by the Python GC, but the GC does not run sufficiently often to prevent the issue.
=> Eliminate reference cycles to improve Ctx cleanup

tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py, tiledb/tests/test_multi_index.py
Retry incomplete queries as long as bytes are being returned, updating
buffers appropriately between query_submit calls.
- fixes #245
- follow up to #238
=> Incomplete query support for standard indexing

misc/azure-ci.yml, tiledb/highlevel.py, tiledb/indexing.pyx, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
- initialize `default_ctx` lazily, allowing user control over global per-process settings when necessary (e.g. `sm.num_tbb_threads`)
- `default_ctx` may be initialized with custom settings by calling `tiledb.libtiledb.initialize_ctx()`
- TBB uses the thread count set at the *first* pool creation, so a call to `tiledb.Ctx(...)` should specify number of threads (if needed) whenever called before an implicit call to `default_ctx()` (unlikely)
- make `default_ctx` a delayed call in all method definitions
- add support for user-controlled initial buffer sizes for queries with unknown result sizes, using new `py.init_buffer_size` parameter
=> Default ctx initialization improvements, and custom buffer size

azure-pipelines.yml, misc/azure-ci.yml, misc/azure-libtiledb-darwin.yml, misc/azure-print-logs.yml, misc/azure-release.yml
Adds a wheel-build script running on azure pipelines and utilizing cibuildwheel. Currently this is run for macOS only, because the `misc/pypi_linux` Docker setup needs some reorganization before I can run it in a similar way.
Fixes #144 
macOS wheels for 0.5.4 were built with this method and uploaded to PyPI: https://pypi.org/project/tiledb/#files (uploaded manually for now, until the Linux side is added).
=> Add wheel builder scripts for macOS

tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
Remove unused code which caused a failure when reading time
ranges with 'ms' units. Existing tests only covered 'ns' units
in this case, and the unused code failed with 'ms' units due to
a difference in NumPy (?) conversion rules, despite having the
same underlying representation:
```
>>> import numpy as np
>>> start = np.datetime64(0, 'ns')
>>> int(start)
0
>>> start = np.datetime64(0, 'ms')
>>> int(start)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'datetime.datetime'
int() argument must be a string, a bytes-like object or a number, not 'datetime.datetime'
>>> start = np.datetime64(1000, 'ns')
>>> start.astype(int)
1000
>>> start = np.datetime64(1000, 'ms')
>>> start.astype(int) …
```
=> Fix #260 and add test for all numpy time units

tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
This was implemented as a Cython method overload, which AFAICT only
works for Cython C++ classes.
```
%load_ext cython
```
```
%%cython
cdef class Foo(object):
def p(self, int p):
print("got int p: ", p)
def p(self, str s):
print("got str s: " , s)
f = Foo()
f.p(1)
f.p("abc") # error
```
=> Support domain.dim('dim name')

HISTORY.md, environment.yml, misc/azure-ci.yml, requirements.txt, tiledb/__init__.py, tiledb/dataframe_.py, tiledb/tests/check_csv_dir.py, tiledb/tests/common.py, tiledb/tests/test_pandas_dataframe.py
Adds functions to create a TileDB array from dataframes and CSV files,
with schema created automatically (if possible, or else error)
- tiledb.from_dataframe accepting a Pandas dataframe
- tiledb.from_csv
Adds function to load a TileDB array as a pandas dataframe, using
metadata for non-primitive type representations when available.
- tiledb.open_dataframe
CSV functionality is manually tested against the [pandas CSV test files](https://github.com/pandas-dev/pandas/tree/master/pandas/tests/io/data/csv) using the included `check_csv_dir.py` file.
=> Add dataframe and CSV i/o helper functions

tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py, tiledb/tests/test_multi_index.py
NumPy scalar slicing is supported (#253). However, there are still some cases
where the NumPy type promotion rules end up coercing the inputs to
float, such as `[np.uint64(0) : 1]` (whereas `np.int64(0):1` works
fine).
Fixes #253
=> Improve tests and error messages for mixed-input slicing

HISTORY.md, examples/vfs.py, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
This PR fixes a number of problems with the FileIO wrapper class which prevented using it with other Python libraries expecting a file-like object for input. In particular, these changes make it possible to pass a FileIO object to pandas and successfully read the content (test added with a TextIOWrapper around a generated local file; manually tested against an S3 VFS).
---
- inherit from RawIOBase
- fix spelling of `writable` (this is checked by various io wrappers)
- fix spelling of `_read_only` -> `read_only` in internal assignment
- fix `readinto` to take any memoryview-like object instead of only `bytes`
- accept `rb`/`wb`/`ab` modes only (not sure if HL callers use this, but we should not lie about being usable as a text i/o)
- fix `readinto` to read up to the length of the given …
=> Clean up FileIO for better compatibility with RawIOBase

HISTORY.md, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
Fixes crash when the name of a non-existent attribute is passed to `tiledb.open` (via https://github.com/dask/dask/issues/5915).
Also reduce specificity for a schema load `try..catch` block because the array should be freed for any exception, and add a test for the schema load failure condition.
=> Fix and test tiledb.open KeyError path for non-existent attribute

tiledb/dataframe_.py
This was preventing passed tiledb_configs from being used (mainly s3 access keys or cloud auth parameters)
=> Use passed ctx for writting in from_dataframe

tiledb/libtiledb.pyx, tiledb/tests/common.py, tiledb/tests/test_libtiledb.py
This change adds a printout of the attribute name if an input variable cannot be converted to NumPy when writing to a sparse array; previously it was difficult to determine which input was failing (e.g. when working with many attributes in a dataframe from `read_csv`).
plus two other small fixes
- print `dtype` repr as quoted string
- check calculated step in `tests.common.intspace` helper
=> Improve type check and error reporting for sparse assignment

tiledb/__init__.py, tiledb/libmetadata.pyx, tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py, tiledb/tests/test_metadata.py
- Sync up metadata empty-val indicator with core libtiledb
- Avoid anonymous dim names in Domain constructor
- automatically constructs sequentially-numbered `__dim_N` named dimensions when all dimension names are given as empty. This expands existing behavior for automatic `from_numpy` dimension naming.
- Add support for `tiledb_array_vacuum` and update related tests
=> Core update/sync 1

tiledb/libtiledb.pyx
This fixes a case where for dimensions which are fixed length and end_buf_ptr is not set resulting in:
`nboundLocalError: local variable 'end_buf' referenced before assignment`
=> Set start/end_buf_ptr for var size nonEmptyDomain

.readthedocs.yml, misc/azure-ci.yml, requirements.txt, requirements_dev.txt
The RTD image seems to no longer provide cmake, so we need to pull it in from PyPI in order to build the docs. Also clean up the requirements/requirements_dev split.
=> Update Readthedocs configuration

tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
- Use correct nonempty_domain code-path for all heterogeneous arrays.
- Return variables for the nonempty range now match the dim dtype.
Previously returned bare integers for a time-typed dimension.
- Tests for above and minor clean-up.
=> Fixes for nonempty_domain with heterogeneous dims

tiledb/dataframe_.py, tiledb/libtiledb.pyx, tiledb/np2buf.pyx, tiledb/tests/common.py, tiledb/tests/test_pandas_dataframe.py
- Add support for correctly round-tripping pandas dataframe indexes as dimensions when read-back using `tiledb.open_dataframe`.
- `tiledb.from_dataframe`/`.from_csv` support for creating ArraySchema with Dims created automatically from Pandas MultiIndex
- Add `multiindex_dims` test
- Add `dataframe_index_to_sparse_dims` test
- Add datetime64 helper function for test generation, and fix issues found w/ datetime64 type translation
=> Add support for read_{csv/dataframe} as sparse array w/ dimensions from MultiIndex

requirements_dev.txt
manylinux1 wheels are available again, and this allows wheel installation on other platforms where wheels were *not* available for 3.13.
=> Remove cmake pin in requirements_dev

tiledb/dataframe_.py, tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py, tiledb/tests/test_pandas_dataframe.py
This change adds support for `read_csv(..., mode='schema_only')`, which will read `nrows` rows and create a schema with matching dims/attributes *without* writing any data to the array.
[ch2471]
=> Add support for read_csv creation with mode=schema_only

HISTORY.md, tiledb/dataframe_.py, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py, tiledb/tests/test_pandas_dataframe.py
- Use attr and coords compression by default for from_csv
- Deprecate and rename tiledb.from_dataframe -> from_pandas
- Fix copy assignment warning from pandas
- Add deprecation warning for open_dataframe
- Remove implicit dict order requirement for multi-attr assignment
=> More CSV updates

tiledb/libtiledb.pyx, tiledb/tests/common.py, tiledb/tests/test_libtiledb.py
- Passing Ddomain=(None,None) will use the full dtype domain, except for
representations which must fit the domain range in uint64 (add +1 to
INTMIN for this case)
- Also adjust rand_datetime64 test helper to use cleaner typemin/max
generation for datetime64.
=> Support Dim(domain=(None,None)) to use full dtype domain

tiledb/libmetadata.pyx
Cython now needs to know the type of the variable reference.
=> Fix build against cython 0.29.20 (latest)

tiledb/core.cc, tiledb/dataframe_.py, tiledb/libtiledb.pyx, tiledb/multirange_indexing.py, tiledb/tests/test_core.py, tiledb/tests/test_pandas_dataframe.py
Using `full_domain` support added in #338 and #342, `from_csv` now allows chunked ingestion into a dense array. The chunking dimension is along `rows` only, with unlimited domain, therefore reads must request the `nonempty_domain` or a subset rather than `[:]`.
=> Add support for chunked CSV read into dense array

tiledb/libtiledb.pyx
Adds optional argument to `default_ctx`, allowing to both retrieve and initialize (once) the global configuration via single function. Deprecates the previous functionality provided by `libtiledb.initialize_ctx`.
=> Add default_ctx support for Config argument

tiledb/core.cc, tiledb/multirange_indexing.py, tiledb/tests/test_libtiledb.py, tiledb/tests/test_multi_index.py, tiledb/tests/test_pandas_dataframe.py
- Improve multi_index query/coords behavior
- Don't return coords for dense multi_index by default (#347) [ch2652]
- Fix and test coords exclusion for sparse array queries [ch2650]
- Fix buffer exclusion when specifying attribute subset
=> Improve multi_index query/coords behavior

tiledb/dataframe_.py, tiledb/tests/test_pandas_dataframe.py
The argument will be applied via pandas.DataFrame.fillna, before
any values are passed in to the TileDB writer. ([example](https://github.com/TileDB-Inc/TileDB-Py/compare/ihn/fillna?expand=1#diff-970d04aaca2ebc4aaa52a1eadbf53db9R488))
=> Add support for from_csv 'fillna' argument

HISTORY.md, doc/source/conf.py, misc/azure-libtiledb-darwin.yml, misc/azure-release.yml, misc/pypi_linux/Dockerfile, misc/pypi_linux/Dockerfile2010, tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
Adds manylinux2010 wheel release target, with Google Cloud Storage enabled.
Addresses #361.
=> Release 0.6.5: add wheel support for GCS

tiledb/core.cc, tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/multirange_indexing.py, tiledb/tests/test_core.py
Buffer(s) will be used to satisfy any subsequent indexing/query request,
until `A._set_buffers(None)` is called.
=> Support attaching external result buffers to Array

tiledb/dataframe_.py, tiledb/tests/test_pandas_dataframe.py
This PR implements support for `tiledb.from_csv` to accept a list of CSV files as the first input argument, instead of a single filename. This ingestion mode requires the `chunksize` argument, which will determine the minimum number of rows to read before flushing to disk.
=> Add support for multi-file CSV ingestion

tiledb/core.cc, tiledb/tests/test_core.py
Provides more Pythonic error rendering.
=> Use std::invalid_argument -> ValueError for config errors

doc/source/conf.py, doc/source/python-api.rst, tiledb/dataframe_.py, tiledb/highlevel.py, tiledb/libtiledb.pyx
=> Docs update: clarify, add missing functions, misc fixes

tiledb/core.cc, tiledb/dataframe_.py, tiledb/tests/test_pandas_dataframe.py
- Revert "Bump default initial buffer allocation to 100 MB"
100 MB is too large for smaller instance types when opening an array
with >10 columns. User will need manual config for now, and we will
revisit with a more sophisticated approach to account for available
memory at runtime.
- Allow open_dataframe to take a Ctx parameter [ch2767]
=> Updates: `open_dataframe` ctx keyword arg; revert a56d919

tiledb/core.cc
The resize algorithm to increase the capacity of buffers was tied to checking the remaining capacity of the data buffer. For variable
length fields, the offset buffer needs to be checked independently.
We encountered an array in which a string field which has a single character. Since this is 1 byte in length, but offsets are 4
bytes in length, we ran out of offset room in the buffer before we had enough data to force a resize.
=> Check for resizing offset buffers independently

tiledb/libtiledb.pyx, tiledb/multirange_indexing.py, tiledb/tests/test_libtiledb.py
- add missing path for properly-typed, empty array return values for empty sparse
varlen results
- fix np.str_ -> np.bytes_ to ensure typed empty array for np.bytes_
data (np.str_ == np.unicode_)
=> Fixes for sparse+varlen with empty result

HISTORY.md, tiledb/dataframe_.py, tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/multirange_indexing.py, tiledb/tests/test_pandas_dataframe.py
Adds a new indexing operation to `tiledb.Array` which returns query results directly as a Pandas dataframe.
Example:
```
In [1]: import tiledb, pandas as pd, numpy as np
...: uri = "/tmp/dfx"
...:
...: d = {'abc': np.random.rand(4),
...:      'xyz': np.random.randint(4)}
...:
...: tiledb.from_pandas(uri, pd.DataFrame.from_dict(d))
...:
...: a = tiledb.open(uri)
...: a.df[0:3]
Out[1]:
rows       abc  xyz
0     0  0.014653    2
1     1  0.205917    2
2     2  0.092197    2
3     3  0.216491    2
```
=> Add `Array.df[]` indexer: directly return dataframe from indexing query

HISTORY.md, tiledb/dataframe_.py, tiledb/tests/test_pandas_dataframe.py
This PR implements the following for from_csv and from_pandas
- 'capacity' kwarg to apply to schema
- 'tile' as dict kwarg (in addition to existing scalar usage) optionally specifying per-dimension tile extents by `{name: extent}` pairs
=> Add support for 'capacity' as kwarg and 'tile' as dict of extents (from_csv/pandas)

tiledb/dataframe_.py, tiledb/libtiledb.pyx, tiledb/tests/test_pandas_dataframe.py
This change hides the 'rows' name we use for generated schema dimension name when no index is specified. A read-back dataframe using `.df[]` or `open_dataframe` should look the same as a direct `pd.read_csv` of the source data. See before/after here: https://github.com/TileDB-Inc/TileDB-Py/compare/ihn/df_readback_rows_x?expand=1#diff-1e19c4fe9825fc13a5d649c9d7745a2d49f2c9be3a247f7fa9b0526fc7ac5142L4131-R4138
By request, and also fixes a bug @eddelbuettel noticed running a prior notebook (plus improved reporting for that error by throwing instead of giving a context-free `assert`ion).
=> Make 'rows' dimension transparent in dataframe read-back

examples/using_tiledb_stats.py, tiledb/core.cc, tiledb/libtiledb.pxd, tiledb/libtiledb.pyx
Previously, tiledb_stats_dump() output to stdout. However, Jupyter notebooks
do not capture or redirect external stdout and thus were not able to display
internal stats. tiledb_stats_dump() now outputs to a temporary file which is
then converted to a Python string.
---
[ch3357]
=> Modified stats_dump() To Return Internal Stats As String

HISTORY.md, tiledb/dataframe_.py, tiledb/multirange_indexing.py, tiledb/tests/test_pandas_dataframe.py
Fixes the last issue with #408 (I added a work-around there for [ch3767]).
closes [ch3779]
=> Use nonempty_domain for open_dataframe whole-array loading

tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/multirange_indexing.py, tiledb/tests/test_pandas_dataframe.py
PR expands the `.df[]` indexer to support use with a `query`: `A.query(attrs=['time']).df[ ... ]`.
As with `Array.df[]`, semantics are the same as `multi_index` and the result is returned as a pandas dataframe.
[ch3834]
=> Add support for query(...).df[] indexing

tiledb/__init__.py, tiledb/libtiledb.pyx
- Fix error condition 'return' -> 'raise'
- Note on fix for Cython line numbers in Jupyter
=> Fix error condition 'return' -> 'raise'; cython backtrace note

HISTORY.md, misc/pypi_linux/build.sh
Add missing cp39 section to the linux wheel build script.
=> Add CPython 3.9 builder section for manylinux wheels

requirements_dev.txt, tiledb/core.cc, tiledb/dataframe_.py, tiledb/libtiledb.pyx, tiledb/multirange_indexing.py, tiledb/tests/test_libtiledb.py, tiledb/tests/test_pandas_dataframe.py
- Add version check for dataframe dependencies to avoid various column type errors observed with pandas < 1.0
- Don't pass allows_duplicates=True to dense array constructor
- Add check for existing array URI before any CSV/dataframe ops (potentially i/o-intensive before getting to array creation error)
- Test and fix unordered query for multi_index/df
=> More dataframe updates

HISTORY.md, tiledb/core.cc, tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/multirange_indexing.py, tiledb/tests/test_core.py, tiledb/tests/test_libtiledb.py, tiledb/tests/test_multi_index.py, tiledb/tests/test_pandas_dataframe.py
- Add support for sub-selection of dimensions to return, via `A.query(dims=[...])`. Previously, the only controlling option `coords=True`, which returned all dimensions. `coords=True` is still supported for backward compatibility.
- Add support for query(index_col=...) keyword arg
This option allows to select dimensions or attributes to set as index(es) when
returning a dataframe, or prevent setting any index at all based on saved
array metadata.
=> Support new A.query(dims=..., index_col=...) keyword args

HISTORY.md, misc/azure-ci.yml, tiledb/core.cc, tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py, tiledb/tests/test_pandas_dataframe.py
- Add test for nonempty_domain with heterogeneous (string, float) dims
- Add support for attribute fill values
- Fix and test error for query(attrs=[],dims=[]) invalid selection
- Add version printouts to stats_dump, and minor cleanups
=> Add nonempty_domain test, Attr fill values, query fix

tiledb/core.cc
This updates use of the returned result from `query->est_result_size_var()` to the current type `std::array<>`.
=> update est_result_size_var() result to std::array

HISTORY.md, misc/azure-release.yml, tiledb/core.cc, tiledb/libtiledb.pyx
Syncing from [0.7.4](https://github.com/TileDB-Inc/TileDB-Py/tree/release-0.7.4)
- bug fix for Dim constructor found during testing the release
- HISTORY.md sync
- a compatibility fix for 2.1.3 to simplify cherry-picking when we do a 0.7.5 (the FragmentInfo changes are self-contained other than setup.py, so they are easy to revert on the release branch)
=> Sync changes from release-0.7.4

tiledb/libtiledb.pxd, tiledb/libtiledb.pyx
* By default, stats_dump() will display top-level information that is
most relevent to end users.
=> Add Verbosity Flag To stats_dump()

tiledb/dataframe_.py, tiledb/multirange_indexing.py
* The wraparound arithmetic is intentional and handled correctly but
still triggers Numpy's overflow warning.
=> Suppress Overflow Warning When Performing Modular Arithmetic

misc/azure-ci.yml, setup.py, tiledb/core.cc, tiledb/debug.cc, tiledb/fragment.cc, tiledb/npbuffer.cc, tiledb/tests/test_fragment_info.py
- Fix object lifetime in array->buffer write
- Fix read compatibility for empty strings written with 2.1 or 2.2
- Misc fixes for concurrent compatibility with libtiledb 2.1/2.2
- Add CI entry for libtiledb 2.1
=> Bug fixes; concurrent compatibility for libtiledb 2.1/2.2

tiledb/core.cc, tiledb/multirange_indexing.py
This PR adds an asynchronous call to array.metadata_num before
submitting the query in the `.df` path.
We unconditionally check `array.meta` in the `.df` path in order
to get any type mappings stored there. This currently happens
synchronously after the query submission, which requires more
network i/o calls to get metadata, because libtiledb metadata
loading is lazy. Instead, initiate an async metadata operation
so that libtiledb fetches (and caches) the metadata ahead of
time.
=> Preload array metadata in the dataframe query path

HISTORY.md, MANIFEST.in, misc/azure-release.yml, misc/pypi_linux/build.sh, setup.py, tiledb/tests/test_libtiledb.py
Sync with `0.8.2` which was tagged and uploaded after full CI+release job build on this commit.
- https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=9359&view=results
- https://dev.azure.com/isaiahnorton/isaiahnorton/_build/results?buildId=509&view=results
=> Sync with release-0.8.2

HISTORY.md, setup.py, tiledb/core.cc, tiledb/multirange_indexing.py, tiledb/tests/common.py, tiledb/tests/test_multi_index.py
Fix bug in Array.multi_index with slice range including 0 (incorrectly used the nonempty domain as endpoint)
=> Fix and test multi_index bug with ranges at 0

tiledb/core.cc, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
If a query range only returns empty strings for a var-length attribute, then
the data buffer will have zero-length and the offsets denote the empty
cells. Remove the zero-length check. See:
https://github.com/TileDB-Inc/TileDB/blob/dev/test/src/unit-empty-var-length.cc
=> Fix read of query returning only empty var-length strings for attribute

tiledb/array.py
These subclasses were set to copy the docstring of Array, which is confusing and incorrect.
=> Fix docstring for DenseArray and SparseArray

tiledb/dataframe_.py
* from_csv()'s `tile` takes in a dictionary structure that maps keys of type str representing column names to values of type int representing tiles -- not a tuple
* Corrected typo `versoin` to `version`
=> Update Documentation For from_csv() To Correct `tile` Input Type

tiledb/fragment.cc, tiledb/tests/test_fragment_info.py, tiledb/tests/test_libtiledb.py, tiledb/tests/test_pandas_dataframe.py
Remove non_empty_domain_var() Fragment Info PyBind11 Function
* This has now been consolidated into get_non_empty_domain().
=> Remove non_empty_domain_var() Fragment Info PyBind11 Function

HISTORY.md
=> Add HISTORY note for TileDB 2.2.6

tiledb/dataframe_.py, tiledb/libtiledb.pyx, tiledb/tests/test_pandas_dataframe.py
Fixes the following bugs:
- `fillna`: https://github.com/TileDB-Inc/TileDB-Py/commit/4256a976c8d52f3911f81d42ac74b1bd8b722064
- Don't mutate the input dataframe
- `date_spec`: https://github.com/TileDB-Inc/TileDB-Py/pull/516/commits/6394edd5db8a6ab749cd063709cee362e7fa6ee6
- Don't mutate the input dataframe
- Always store the `date_spec` attributes as `datetime`
The previous commits are unrelated refactorings.
=> tiledb.from_pandas fixes for fillna and date_spec

HISTORY.md, tiledb/dataframe_.py, tiledb/tests/datatypes.py, tiledb/tests/test_pandas_dataframe.py
This PR adds support for storing dataframe columns as TileDB [var-length attributes](https://docs.tiledb.com/main/solutions/tiledb-embedded/api-usage/writing-arrays/var-length-attributes). It introduces a new optional parameter for `tiledb.from_pandas`, `varlen_types`, a set of Pandas extension dtypes to be stored as var-length attributes. An extension dtype is considered to be var-length if the result of calling `to_numpy()` on a pandas Series of this dtype returns a "ragged array", a numpy array of arrays.
All the var-length changes are contained in the [last commit](https://github.com/TileDB-Inc/TileDB-Py/commit/ee9cb97767b0feadbdf4a3487edef54065c35020), the previous commits are refactorings.
=> Variable length attribute support for Pandas extension types

.github/workflows/ci.yml, examples/parallel_csv_ingestion.py, misc/azure-ci.yml, misc/requirements_ci.txt, requirements_dev.txt, tiledb/highlevel.py, tiledb/npbuffer.cc, tiledb/tests/test_dask.py
- fixes [ch6276], a crash due to incorrect object lifetime in conversion path leading to rare use-after-GC
- ensure actually running, and fix, the full `parallel_csv_ingestion` test (was previously only running the `example()` write path, because the test is not discoverable)
=> Fix intermittent crash due to incorrect pybind11 object scope

tiledb/dataframe_.py, tiledb/multirange_indexing.py, tiledb/tests/test_multi_index.py, tiledb/tests/test_pandas_dataframe.py
Extensive refactoring of the `multirange_indexing` module. Better reviewed on a commit-by-commit basis as the whole module has been touched.
- Reduce the state surface of the `MultiRangeIndexer` and `DataframeIndexer` classes by converting most private methods to standalone functions.
- Break up long functions to smaller ones.
- Remove duplicate logic, e.g. in determining the pandas dataframe index. Line count reduced by ~150 in total.
- Tighten the checks and conversions of input `idx` to ranges. 
- Add a `timing` context manager.
- Add type annotations.
=> Multirange indexing refactoring

pytest.ini, tiledb/tests/common.py, tiledb/tests/test_compat.py, tiledb/tests/test_core.py, tiledb/tests/test_dask.py, tiledb/tests/test_libtiledb.py, tiledb/tests/test_pandas_dataframe.py, tiledb/tests/test_util.py
- replace `unittest.TestCase` base class with standalone DiskTestCase
class (implementing the assert methods we use)
- allows using pytest parameterization on any test, which is not
possible with subclasses of unittest.TestCase
=> Refactor tests to use pytest only

tiledb/__init__.py, tiledb/dataframe_.py, tiledb/multirange_indexing.py, tiledb/tests/test_multi_index.py, tiledb/tests/test_pandas_dataframe.py
- Introduce `tiledb.EmptyRange` sentinel value to denote an empty slice range.
- `A.multi_index[tiledb.EmptyRange]` returns a dict with values 0-length `np.array`s with the expected `dtype`.
- `A.df[tiledb.EmptyRange]` returns an empty `pd.DataFrame` with the expected column/`dtypes`.
Also extend `tiledb.open_dataframe` with an optional `idx` parameter (default=full range `slice(None, None)`).
=> Support returning empty result from MultiRangeIndexer and DataFrameIndexer

pytest.ini
GHA CI is consistently hanging, and after some [debug builds](https://github.com/TileDB-Inc/TileDB-Py/actions/runs/756722444) it appears the problem may be due to recursing into .git.
=> Try to fix hanging CI: don't let pytest recurse into .git [ch6686]

pytest.ini
Overriding `norecursedirs` removes some useful defaults, so try specific ignore paths instead.
=> Retry pytest recurse/exclude options

examples/incomplete_iteration.py, tiledb/core.cc, tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/multirange_indexing.py, tiledb/tests/fixtures.py, tiledb/tests/test_libtiledb.py
- Adds a new `Array.query` option `return_incomplete` to enable iteration over incomplete results (rather than running queries to completion by reallocating buffers and resubmitting, as is the default).
- When enabled, indexing the `query` returns an iterator which will return results for each incomplete query as consumed. Example:
```
with tiledb.open(uri) as A:
for df in A.query(return_incomplete=True).df[slice_start:slice_end]:
print(df) # df is a pandas DataFrame
```
- Adds usage example in `examples/incomplete_iteration.py`
- Also adds `estimated_result_sizes` getter to return estimated buffer sizes (from `tiledb::Query::est_result_size_*`) on the _initialized_ iterator object.
=> Add support for iterating over incomplete queries

tiledb/libtiledb.pyx
This uses `{!r}` to get `repr` for the tiling rather than `str` (which returns eg `600 seconds` for `timedelta64(600,'s')` -- the latter cannot be parsed.
=> Fix Domain tile representation round-tripping

requirements.txt, setup.py, tiledb/__init__.py, tiledb/ctx.py, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
Most `tiledb` functions and classes accept an optional `ctx` parameter. This is less than ideal for the following reasons:
- **Verbose**
Taking [examples/string_float_int_dimensions.py](https://github.com/TileDB-Inc/TileDB-Py/blob/dev/examples/string_float_int_dimensions.py#L43) as an example, `ctx` is initialized and passed to 6 different calls:
```
ctx = tiledb.Ctx()
dom = tiledb.Domain(
*[
tiledb.Dim(name="str_dim", domain=(None, None), dtype=np.bytes_, ctx=ctx),
tiledb.Dim(name="int64_dim", domain=(0, 100), tile=10, dtype=np.int64, ctx=ctx),
tiledb.Dim(
name="float64_dim",
domain=(-100.0, 100.0),
tile=10,
dtype=np.float64,
ctx=ctx,
),
],
ctx=ctx
)
att = tiledb.Attr(name="a", ctx=ctx, dtype=np.int64)
schema = tiledb.ArraySchema(
ctx=ctx, domain=dom, attrs=(att,), sparse=True, …
```
=> Ctx context manager and ContextVar

HISTORY.md, misc/azure-ci.yml, tiledb/core.cc
=> Fix segfault due to mismatched validity num and data buffer sizes

tiledb/core.cc, tiledb/libtiledb.pyx, tiledb/tests/fixtures.py, tiledb/tests/test_libtiledb.py, tiledb/util.py
- Fixes #572, due incorrect type used in `add_range` template call
- Adds regression tests for indexing with all integer dimension types
=> Fix incorrect type for add_range with int8 dimension

setup.py
setup.py is distributed in source bundles, and defaults here are used in end-user builds from source.
=> Disable Werror by default in setup.py

setup.py
Via user request to build on linux/aarch64 (ubuntu 20 on raspberry pi 4)
These requirements need to be applied during packaging for ABI compatibility, but should
not be applied to end-user builds-from-source. Pinned NumPy versions may not have binary
wheels available, forcing a build of *NumPy* from source (likely to fail due to
extensive dependencies). eg NumPy wheels are available on linux/aarch64
NumPy 1.20 but not 1.16.
=> Relax numpy requirements in setup.py

examples/string_float_int_dimensions.py, examples/variable_length.py, tiledb/dataframe_.py, tiledb/highlevel.py, tiledb/tests/fixtures.py, tiledb/tests/test_compat.py, tiledb/tests/test_core.py, tiledb/tests/test_fragment_info.py, tiledb/tests/test_libtiledb.py, tiledb/tests/test_metadata.py, tiledb/tests/test_multi_index-hp.py, tiledb/tests/test_multi_index.py, tiledb/tests/test_pandas_dataframe.py, tiledb/tests/test_util.py
Follow up from https://github.com/TileDB-Inc/TileDB-Py/pull/563:
- Drop unused or redundant explicit `ctx` from tests and examples and replace most remaining `tiledb.Ctx()` with `tiledb.scope_ctx()`.
- Ensure `tiledb.from_pandas()` uses the same `ctx` via `tiledb.scope_ctx()`
=> Use scope_ctx in from_pandas and in tests

HISTORY.md, tiledb/core.cc, tiledb/tests/test_core.py, tiledb/tests/test_defects.py
- Fix and add test for ch7727
- Correctly cap offset and validity buffer allocations in case of estimate overflow
- Set minimum for `alloc_max_bytes_` parameter to 1 MB or error out
=> Fix ch7727: correctly cap offset and validity buffer allocations

tiledb/libmetadata.pyx
C API call `tiledb_array_consolidate_metadata_with_key` does not function correctly in libtiledb 2.3 if `config=nullptr`. Fix is to explicitly specify the config so that the `sm.consolidation.mode: array_meta` setting is passed through.
=> Fix ch7693

misc/azure-ci.yml, setup.py, tiledb/core.cc, tiledb/fragment.cc, tiledb/npbuffer.cc, tiledb/query_condition.cc, tiledb/util.h
This PR fixes all errors in C++ code under `-Werror`, and enables that option. Cython currently excluded.
=> Fix warnings on clang and gcc

tiledb/dataframe_.py, tiledb/multirange_indexing.py, tiledb/tests/test_pandas_dataframe.py
Fix `tiledb.from_pandas` to support different index dimensions through the `index_dims` parameter.
=> Fix index dims parameter for tiledb from pandas

tiledb/dataframe_.py
If the array is sparse then we don't need to require 'row_start_idx'.
=> Relax from_pandas 'append' requirement for 'row_start_index'

tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
tiledb.Array.open `timestamp` kwarg now supports a tuple of `(start: Int, end: Int)`
to open the array within a specific timestamp range.
Example:
```
with tiledb.open(path, timestamp=(1234, 5678)) as A:
... # read A considering only fragments between
```
The existing `timestamp: Int` kwarg signature is unchanged.
=> Add Array.open support for timestamp ranges

.gitignore, HISTORY.md, doc/local-build.sh, misc/azure-release.yml, misc/requirements_wheel.txt, requirements.txt, requirements_dev.txt, setup.py, tiledb/__init__.py, tiledb/core.cc, tiledb/dataframe_.py, tiledb/debug.cc, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
- Bump version to 0.9; libtiledb target to 2.3.0
- Remove deprecated function `from_dataframe`
- Improve `requirements{,_dev/_wheel}.txt` setup.py handling to allow single source of truth
- Add doc for `est_result_size` with Query(return_incomplete=True)
- Misc other fixes
=> Updates for 0.9

conftest.py, misc/azure-ci.yml, pyproject.toml, pytest.ini, tiledb/libtiledb.pyx, tiledb/tests/common.py, tiledb/tests/test_compat.py, tiledb/tests/test_fragment_info.py, tiledb/tests/test_libtiledb.py, tiledb/tests/test_pandas_dataframe.py
This PR makes it possible to run TileDB-Py tests against S3, replacing the sketch in #396. A new `--vfs` (default `"file"`) parameter is configured in pytest, used as:
```
pytest --vfs=s3
```
which will currently use local minio settings corresponding to the settings in the core `scripts/run-minio.sh` script.
Some tests are modified to run correctly against S3, for example using `tiledb.FileIO` and `tiledb.VFS` for directory and r/w file operations respectively, instead of using python local filesystem functions. A handful of tests are skipped if not feasible to modify at this point (eg it seems that `tiledb.Config` does not support loading a config from a URI).
=> Enable running TileDB-Py tests against s3

tiledb/tests/common.py, tiledb/tests/conftest.py, tiledb/tests/test_dask.py, tiledb/tests/test_examples.py, tiledb/tests/test_libtiledb.py
This PR adds a fixture to use pytest capturing in order capture all stdout, for two
use-cases:
(1) by default assert that no output is written
(2) if capfd is manually requested for test, we can get
override the no_output assertion and check
for expected output (when using functions that are expected
to write to stdout)
Important details:
- capfd does not flush, so we use libc.fflush to ensure that capfd
actually gets all output
- for test_examples, we need to add a no-op `no_output` signature
which does not take capfd; otherwise, there will be a conflict
with the usage of capsys in test_docs
=> Check test output

doc/local-build.sh, doc/requirements_doc.txt
I forgot that readthedocs requires cmake to be installed manually because it (currently) builds libtiledb from source.
Add a new doc/requirements_doc.txt file to make pip install cmake as part of the rtd build.
(cmake from pip was just removed in commit 30c60fcbe74)
=> Fix readthedocs build

misc/requirements_test.txt, tiledb/multirange_indexing.py, tiledb/tests/datatypes.py
I suspect this is a Pandas [bug](https://github.com/pandas-dev/pandas/issues/42501); for now just override the `copy` method of `RaggedArray`.
=> Temporary(?) fix of test_var_length broken on pandas 1.3.0

misc/azure-libtiledb-darwin.yml, misc/azure-release.yml
- set TILEDB_WHEEL_BUILD to make sure we use the correct requirements.txt file for numpy pinning
- disable libtiledb caching for release builds to ensure that all platforms/builds are strictly updated
- set CXXFLAGS/CFLAGS at the job level for linux only so they are not used on macOS
=> Wheel build fixes for 0.9.3

misc/azure-libtiledb-darwin.yml, misc/azure-release.yml, misc/requirements_wheel.txt
The test I added doesn't seem to do what I had hoped for (I think it installs newer numpy despite the CIBW_BEFORE_TEST), but I manually tested all of the linux wheels here against the oldest supported numpy versions: https://dev.azure.com/isaiahnorton/isaiahnorton/_build/results?buildId=636&view=artifacts&pathAsName=false&type=publishedArtifacts
=> Use TILEDB_WHEEL_BUILD inside CIBW_ENVIRONMENT & other wheel fixes

HISTORY.md, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
* This also fixes a bug where `nonempty_domain` was returning extents of dtype `np.array` instead of scalars.
=> Get `nonempty_domain` Directly From `_nonempty_domain_var`

HISTORY.md, tiledb/query_condition.py, tiledb/tests/test_query_condition.py
* Can now use bitwise & in addition to "and"
* Can do both lhs and rhs for operators (e.g. "3 < x and x < 5"
can now be written as "3 < x < 5")
=> Add More Valid Python Syntax for `QueryCondition` Statements

.github/workflows/ci.yml, setup.py
- This fixes an issue encountered when file paths exceed the maximum limit when using CMake on GHA Windows CI
=> Shorten Build Directory Name in `setup.py` By Truncating `TILEDB_VERSION`

examples/multirange_indexing.py
https://github.com/TileDB-Inc/TileDB-Py/blob/dev/examples/multirange_indexing.py#L56 is apparently an inadvertent copypasta from https://github.com/TileDB-Inc/TileDB-Py/blob/dev/examples/multi_attribute.py#L57
=> Typo-fix in comment in multirange_indexing.py

examples/parallel_csv_ingestion.py
Running straight-from-wiki code samples I see
```
$ python examples/parallel_csv_ingestion.py
Finished generating CSVs in path:  /var/folders/kq/s93hr1xxxftknc0000gn/T/tmpdcd7e5cp
Writing output array to:  /var/folders/kq/s93hr1r15sd47nmw2p4ftknc0000gn/T/tmpaykazzyo
/Users/kerl/git/TileDB-Inc/TileDB-Py/examples/parallel_csv_ingestion.py:222: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
...
```
On this PR I am replacing `np.str` with `str`.
Plusses and minuses:
* Having fewer warnings at runtime is (all else being equal) a cleaner and more reassuring experience for the user
* However, we don't …
=> Avoid np.str runtime deprecation warning

HISTORY.md, examples/fragment_info.py, tiledb/fragment.py, tiledb/tests/test_fragment_info.py, tiledb/tests/test_libtiledb.py
This deprecates functions: 
- `FragmentInfoList.to_vacuum_uri`
- `FragmentInfoList.to_vacuum_num`
- `FragmentInfo.to_vacuum_uri`
- `FragmentInfo.to_vacuum_num`
Including the fragment(s) to  vacuum in `FragmentInfo` was nonsensical. `FragmentInfoList.to_vacuum_uri` has been renamed to `FragmentInfoList.to_vacuum` for simplicity. `FragmentInfoList.to_vacuum_num` no longer exists. Instead, use `len(FragmentInfoList.to_vacuum)`.
=> `FragmentInfoList.to_vacuum` Retrieves URIs of Consolidated Fragments to Vacuum

HISTORY.md, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
* This fixes a bug where appending `None` causes a segfault
=> Check `filter` Argument When Appending to `FilterList`

HISTORY.md, tiledb/multirange_indexing.py, tiledb/tests/test_multi_index.py
* Previously, this operation would error out.
=> Return Empty Result With Empty Nonempty Domain With Multi-Index

HISTORY.md, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
* Errors out when `var=True` but the string is a fixed-width type and when `var=False` but the string is a variable-length type.
=> Improve Checking For Byte-String Attributes

HISTORY.md, tiledb/libtiledb.pyx, tiledb/tests/test_fixes.py
Fixes correctness bugs, especially for concurrent use of indexers from the same Array
object.
=> Use new instance for each multi_index/df invocation

tiledb/tests/test_hypothesis.py
- Split test_bytes into separate tests for df and np paths
- Use hypothesis.note to record stats upon failure
=> Debugging for test_bytes

tiledb/core.cc
Reading an empty result is supported. This path is already tested in
test_pandas_dataframe:test_dataframe_empty, so remove the asserts
which fail in debug build.
Also x-ref sc-10191 and TileDB core PR 2505
=> Remove 'size > 0' assertions in reader path

tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
=> Mark sparse_write_to_dense as xfail with libtiledb 2.5+

tiledb/tests/conftest.py, tiledb/tests/test_hypothesis.py
I am hoping this will address the CI failures in sc-8256 by avoiding variance in the timing of initial calls to `tiledb.open`, but not 100% sure if this is the main issue; see commit message for full explanation.
=> Try to pre-import tiledb.cloud before tests

HISTORY.md, examples/fragment_info.py, setup.py, tiledb/fragment.cc, tiledb/fragment.py, tiledb/highlevel.py, tiledb/tests/test_fragment_info.py
* Retrieve the minimum bounding rectangle for each fragment
* Correct parameter and class attribute documentation for `FragmentInfo{,List}`
* Refactor `PyFragmentInfo` to call `load()` and `close()` in constructor
* Refactor `PyFragmentInfo` to use getter functions to return read-only attributes instead of directly accessing public attributes
=> Addition of MBRs to `FragmentInfo` API

HISTORY.md, tiledb/__init__.py, tiledb/tests/test_libtiledb.py, tiledb/version_.py
- Modified to synchronize with `tiledb.libtiledb.version()`
=> `tiledb.version.version` Returns Version As Tuple

tiledb/tests/test_pandas_dataframe.py
Fixed by https://github.com/TileDB-Inc/TileDB/commit/e40aba3eaf6783fbec290e44ed5e177513e4dc8a -- Thanks @KiterLuc.
=> Remove temporary xfail for test_incomplete_df

tiledb/libtiledb.pyx, tiledb/tests/test_pandas_dataframe.py
Fixes #819
https://github.com/TileDB-Inc/TileDB/pull/2692 removes the __lock file,
so these tests will no longer be compatible with multiple libtiledb
versions (we actively test against dev and last release). Ignore the
file count output.
=> Remove doctest expected output for file count

tiledb/core.cc
Just print all counters so we can add them as needed.
=> Simplify Python internal stats output

tiledb/core.cc
On PyQuery construct cache domain and array schema. This avoid copies occuring during the various function calls. Eventually the C++ API should handle this better, for now this is a minor but quick fix.
=> On PyQuery construct cache domain and array schema

tiledb/core.cc
=> Don't call est_result_size for sparse arrays

.github/workflows/format.yml, HISTORY.md, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
* Allow writing to dimension-only array (zero attributes) by using assignment to `None`, for example: `A[coords] = None` (given `A: tiledb.Array`)
=> Support Writes to Zero Attribute Array

HISTORY.md, tiledb/libtiledb.pyx
* Escape HTML strings for names and dtypes
=> Remove repeating header names for `attr` when displaying `ArraySchema` in Jupyter Notebooks

HISTORY.md, tiledb/libtiledb.pyx
=> Cast Dimension Dtype to String Prior to Apply HTML Escape

HISTORY.md, tiledb/core.cc, tiledb/query_condition.py, tiledb/tests/test_query_condition.py
* Previously, there was no way to apply query conditions to attributes
with spaces. With the addition of the attr() cast, it is now possible to
do `tiledb.QueryCondition("attr('attributes with spaces') == 'val'))`
=> Cast Operands in `QueryCondition` Using attr() or val()

tiledb/query_condition.py
Most errors have been fixed except the following.
```
(tiledb-3.10) vivian@mangonada:~/TileDB-Py$ pyright tiledb/query_condition.py
No configuration file found.
pyproject.toml file found at /home/vivian/TileDB-Py.
Loading pyproject.toml file at /home/vivian/TileDB-Py/pyproject.toml
Pyproject file "/home/vivian/TileDB-Py/pyproject.toml" is missing "[tool.pyright]" section.
stubPath /home/vivian/TileDB-Py/typings is not a valid directory.
Assuming Python platform Linux
Searching for source files
Found 1 source file
/home/vivian/TileDB-Py/tiledb/query_condition.py
/home/vivian/TileDB-Py/tiledb/query_condition.py:296:18 - error: Argument of type "Type[operator]" cannot be assigned to parameter "__k" of type "Type[BitAnd]" in function "__getitem__"
  "Type[operator]" is incompatible with …
```
=> Correct `QueryCondition` Typing Against pyright

tiledb/core.cc, tiledb/multirange_indexing.py, tiledb/tests/test_libtiledb.py
In return_incomplete mode, prior to this PR the multi_index and df indexer
estimated_result_sizes function would error out until iteration was started,
because the underlying query object was not initialized. In this PR we
fix this issue by initializing the query and updating iteration logic
using a state enum.
=> Fix SC-13800: properly initialize query in order to retrieve estimated results

HISTORY.md, misc/azure-release.yml, setup.py, tiledb/tests/test_query_condition.py
```
(tiledb-clean-3.10) vivian@mangonada:~/drop$ python
Python 3.10.0 (default, Dec 21 2021, 13:36:04) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tiledb
>>> tiledb.version()
(0, 12, 3)
>>> tiledb.libtiledb.version()
(2, 6, 3)
>>>
```
=> Release 0.12.3 against 2.6.3

tiledb/fragment.py, tiledb/tests/test_fragments.py
The root cause of SC-15271 was deleting the wrong schema, because
we were removing the _deleted_ schema from the target set when
generating the set difference, leaving only the live schema.
=> Fix delete_fragments and remove xfail

tiledb/core.cc, tiledb/tests/test_fixes.py
This function is not used in any active codepath, only for debugging/testing.
(needed this locally, might as well change it for next time)
=> Return dict from debug function get_buffers

.github/workflows/ci.yml, .github/workflows/daily-test-build.yml
* By default on GitHub actions, all jobs are cancelled when a job fails. 
This setting makes it so that other jobs will continue to run.
=> Set `fail-fast` To `false`

misc/azure-release.yml
These lines are no longer required since the build-system additions to `pyproject.toml`.
=> Remove `CIBW_BEFORE_TEST` Lines

HISTORY.md, misc/azure-release.yml
Note that `setup.py` is already using 2.8.0 (was modified for testing the Group API PR).
=> Release 0.14.0 Against 2.8.0

pyproject.toml
* Otherwise the MacOSX Conda build for Python 3.7 errors out with
`AttributeError: module 'setuptools' has no attribute 'version'`
=> Change `setuptools` Pin From `<=61.0` To `<=59.5.0`

HISTORY.md, misc/azure-release.yml, setup.py
```
(py38) [ec2-user@ip-10-0-116-169 tmp]$ python
Python 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tiledb
>>> tiledb.version()
(0, 14, 1)
>>> tiledb.libtiledb.version()
(2, 8, 1)
```
=> Release 0.14.1 against TileDB 2.8.1

requirements_dev.txt
* This was set in `pyproject.toml` in TileDB-Inc/TileDB-Py#1032 but also
needs to be changed in `requirements_dev.txt`
* This is necessary for the the OSX Python 3.7 Conda builds
=> Set `setuptools` to `<=59.5.0`

tiledb/dataframe_.py
The dtype passed in is likely to be of numpy.dtype when the dtype comes directly from pandas. This means we need to check the type before comparing to the string "ascii".
=> Fix comparison error for pandas dataframe dtype

misc/azure-release.yml, misc/pypi_linux/Dockerfile2010
* Note that this is pinned to the same version in core: https://github.com/TileDB-Inc/TileDB/pull/3111
=> Bump `manylinux2010` Images to `2022-04-24-d28e73e`

requirements_dev.txt, tiledb/core.cc, tiledb/py_arrow_io_impl.h, tiledb/py_arrowio, tiledb/tests/test_multi_index.py
* This fixes an issue where `.query(return_arrow=True)` did not
properly return an Arrow Table due to `~PyQuery` destroying the
NumPy arrays holding the Arrow buffers upon returning from
`multirange_indexing.DataFrameIndexer.__getitem__`. The buffers
are now linked to the lifetime of the PyArrow Table rather
than the `PyQuery` object
* Move `arrow_io_impl.h` from core to `py_arrow_io_impl.h`
* Addition of `BufferHolder` struct to hold `py::object`s `data`,
`offset`, and `validity` which respectively hold the necessary
buffers for the Arrow Table
* In `PyQuery.pa_buffer`, create `BufferHolder` and pass buffers
to increment refcount. Set `CPPArray.cbb_data` to `BufferHolder`
pointer and `CPPSchema.release_cb` to `free_buffer_holder`.
When the Arrow Table destructor is called, …
=> Arrow Buffer Ownership Handoff

tiledb/tests/test_libtiledb.py
Fixes deprecation error
`[2022-05-04 11:44:18.984] [Process: 5350] [error] [Context: 20] Config parameter "sm.num_reader_threads" has been removed; use config parameter "sm.compute_concurrency_level".`
=> Use `sm.compute_concurrency_level` For `libtiledb`>=2.10

.github/workflows/ci.yml, .github/workflows/daily-test-build-numpy.yml, .github/workflows/daily-test-build.yml, HISTORY.md, misc/azure-ci.yml, misc/azure-release.yml
* macOS-10.14 has been deprecated by Azure and Github Actions
=> Use MacOSX 10.15

HISTORY.md, misc/azure-release.yml
```
(tiledb-clean) vivian@mangonada:~/drop$ pip install tiledb-0.14.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Processing ./tiledb-0.14.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Collecting numpy>=1.21.0
Using cached numpy-1.22.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Collecting packaging
Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
Using cached pyparsing-3.0.8-py3-none-any.whl (98 kB)
Installing collected packages: pyparsing, packaging, numpy, tiledb
Successfully installed numpy-1.22.3 packaging-21.3 pyparsing-3.0.8 tiledb-0.14.4
(tiledb-clean) vivian@mangonada:~/drop$ python
Python 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or …
```
=> Release 0.14.4

tiledb/tests/test_multi_index-hp.py
* Core is throwing a new error message for ranges that are out of bounds:
https://github.com/TileDB-Inc/TileDB/commit/563058120c01b258150dfe86faba192a475407f8#diff-cf47a61c916e49adcd1320af3c346b7e710e153118266fe0c580bed858ebba69R328-R330
=> Add New Error Message To `is_boundserror`

tiledb/group.py, tiledb/libtiledb.pyx, tiledb/tests/test_group.py
Context: https://github.com/single-cell-data/TileDB-SingleCell/issues/113
Then this:
https://github.com/single-cell-data/TileDB-SingleCell/blob/836d02a47c6f53d6df5ca77acc081834fc323079/apis/python/src/tiledbsc/tiledb_group.py#L57-L79
will become as simple as it already is for arrays:
https://github.com/single-cell-data/TileDB-SingleCell/blob/836d02a47c6f53d6df5ca77acc081834fc323079/apis/python/src/tiledbsc/tiledb_array.py#L34-L45
=> Add __enter__/__exit__ for TileDB Groups

HISTORY.md, tiledb/core.cc, tiledb/libtiledb.pyx, tiledb/tests/test_hypothesis.py, tiledb/tests/test_libtiledb.py
* Correcting `stats_dump` issues: Python stats now also in JSON form if `json=True`, resolve name mangling of `json` argument and `json` module, and pulling "timer" and "counter" stats from `stats_json_core` for `libtiledb`>=2.3
=> JSON Dump Python Stats

HISTORY.md, tiledb/multirange_indexing.py, tiledb/py_arrow_io_impl.h
* `TILEDB_BOOL` is represented as a `uint8_t` whereas Arrow's Boolean
type is 1 bit
* Use Arrow's uint8 type in `tiledb_buffer_arrow_fmt` for `TILEDB_BOOL`
* Cast Boolean types in the resulting Arrow table in `_run_query` from
uint8 to bool
=> Fix Arrow Table Incorrect Boolean Results

misc/azure-ci.yml
* The macOS build frequently takes more than 60 minutes
=> Increase Azure Devops Timeout To 120 Minutes

HISTORY.md, misc/azure-release.yml
(The `TILEDB_VERSION` in `setup.py` is already set to `2.10.0`.)
=> Release 0.16.0 Against 2.10.0

tiledb/libtiledb.pxd
Building locally ends on a 
> warning: tiledb/libtiledb.pxd:86:8: 'TILEDB_BLOB' redeclared
which this micro-PR improves upon.  No other code changes.
=> Remove duplicated TILEDB_BLOB

tiledb/tests/test_dask.py
* `DeprecationWarning` is being thrown by Dask but should be fixed
by https://github.com/dask/distributed/issues/6163
* Temporarily disabling this test for two weeks as to not trigger
nightly test failures
=> Skip `test_dask_multiattr_2d` Until 2022 July 19

HISTORY.md, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
* Querying dense array with `[:]` returns shape that matches nonempty
domain, consistent with `.df[:]` and .multi_index[:]`
* Previously, the entire domain was returned where values outside of the
nonempty domain contained default fill values
=> Dense Array `[:]` Returns Data From Nonempty Domain Only

HISTORY.md, examples/query_condition_dense.py, examples/query_condition_sparse.py, tiledb/libtiledb.pyx, tiledb/query_condition.py, tiledb/tests/test_query_condition.py
* Remove error for applying `QueryCondition` on dense arrays
* Add testing, documentation, and examples of `QueryCondition` usage on both sparse and dense arrays
* Add missing `TILEDB_STRING_ASCII` to `_tiledb_dtype_to_numpy_typeid_convert`
* Closes [sc-17776]
=> Support `QueryCondition` on Dense Arrays

HISTORY.md, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
The nonempty domain for the `clinvar-annotations` array turns out to be the empty string for the third dimension.
This was discovered whilst debugging ch18654 when queries to this array resulted in `Index out of bounds` exceptions.
This is unrelated though unfortunately with the original problem described in ch1865.
=> Index out of bounds when nonempty domain is empty string

HISTORY.md, misc/azure-release.yml, tiledb/tests/test_libtiledb.py
* This removes `import tkinter` which was preventing the conda
package from building properly
=> Release 0.16.3

setup.py
The conda packages for aarch64 and arm64 do not build correctly when using ctypes to call `tiledb_get_version` from the TileDB shared object library due to a permissions issue. We are reverting back to parsing from `tiledb_version.h`.
=> Go Back To Parsing `libtiledb` Version From `tiledb_version.h`

HISTORY.md, tiledb/cc/filestore.cc, tiledb/filestore.py, tiledb/tests/test_filestore.py
* This function was accidentally left in; it does not work
* The function to write a file located at URI to a filestore array is
already correctly implemented by `Filestore.copy_from`
=> Remove Unused/Extraneous `Filestore.uri_import`

HISTORY.md, requirements_dev.txt
* Fixes issue #1258
* Required for building `libtiledb` as of TileDB-Inc/TileDB#3306
=> Update minimum required `cmake` version to =>3.23

HISTORY.md, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
This reverts commit f7145ede9d1cdc94b42ad2ba13821417b0a190f2.
- The regular indexer should return the entire array, not just the nonempty domain, to maintain NumPy semantics
=> Revert "Dense Array `[:]` Returns Nonempty Domain Only (#1199)"

setup.py, tiledb/tests/test_libtiledb.py
* Remove `\x00` for `test_varlen_sparse_all_empty_strings`
=> [Merge 2.11] Addition of `test_from_numpy_empty_str`

tiledb/tests/test_dask.py
* Allow warning message `make_current is deprecated`
* This warning message is emitted from the Hurricane library via Dask in Python 3.7 on POSIX
=> Add `filterwarning` For `test_dask_multiattr_2d` 

tiledb/tests/test_libtiledb.py
* As of 0.17.0, a warning is emitted when running `test_init_config`
for the aarch64 conda builds with the messsage:
```
<jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
<jemalloc>: (This is the expected behaviour if you are running under QEMU)
```
* This can be ignored as this is being run in a Docker image / QEMU
and is therefore expected behavior
* There was a temporary patch added to 
https://github.com/conda-forge/tiledb-py-feedstock/pull/145
in order to get the aarch64 packages to build properly. This should be
removed in the next release in lieu of this change
=> Add `filterwarning` For `test_init_config`

HISTORY.md, tiledb/query_condition.py, tiledb/tests/test_dask.py, tiledb/tests/test_query_condition.py
* Currently, `datetime64` values in `QueryCondition`s should be casted to UNIX seconds
=> Support `datetime64` For `QueryCondition`

HISTORY.md, tiledb/multirange_indexing.py, tiledb/tests/test_query_condition.py
* Fix issue where querying an array with a Boolean type when `arrow=True`, but is unselected in `.query(attr=...)`, results in an error `pyarrow.lib.ArrowInvalid: Invalid column index to set field.`
=> Fix Bug For Querying With Unselected Boolean Type

HISTORY.md, tiledb/py_arrow_io_impl.h, tiledb/tests/test_multi_index.py
* Previously, this errored out with `ArrowInvalid: Expected 3 buffers for imported type large_binary, ArrowArray struct has 2`
* Fixed-width `TILEDB_CHAR` was using type large binary ("Z") which requires 3 buffers, including an offset buffer, that is not present or necessary for fixed-width binary strings
* This does not handle fixed-width `TILEDB_UTF8`
=> Use Arrow Type Fixed-Width Binary ("w:") For Fixed-Width `TILEDB_CHAR`

HISTORY.md, tiledb/fragment.cc, tiledb/tests/test_fragments.py
Before:
```
johnkerl@ip-192-168-1-183[prod][][~]$ pyttt
tiledbsc.__version__       0.1.11.dev4
tiledb.cloud.__version__   0.7.45
tiledb.__version__         0.17.2
core version               2.11.1
>>> tiledb.array_fragments('krasnow/X/data', include_mbrs=True)
File "/Users/johnkerl/git/TileDB-Inc/TileDB-Py/tiledb/highlevel.py", line 141, in array_fragments
return tiledb.FragmentInfoList(uri, include_mbrs, ctx)
File "/Users/johnkerl/git/TileDB-Inc/TileDB-Py/tiledb/fragment.py", line 103, in __init__
schema = tiledb.ArraySchema.load(array_uri, ctx=ctx)
File "tiledb/libtiledb.pyx", line 2882, in tiledb.libtiledb.ArraySchema.load
File "tiledb/libtiledb.pyx", line 575, in tiledb.libtiledb._raise_ctx_err
File …
```
=> Add Support For Retrieving MBRs Of Var-Sized Dims

tiledb/tests/test_hypothesis.py
- Remove work-arounds for previously unsupported codepath
- Add separate timing and `hypothesis.note` for `from_{numpy,pandas}` step so that we can try to determine if that step is the cause of #1194.
=> Update test_bytes_{numpy,df} to address test failures

tiledb/tests/test_group.py
Fixes
```
>       assert len(grp.meta) == 2
E       AssertionError: assert 3 == 2
E        +  where 3 = len({'flt': (1.5, 2.5, 3.5), 'int': (1, 2, 3), 'str': b'asdf'})
E        +    where {'flt': (1.5, 2.5, 3.5), 'int': (1, 2, 3), 'str': b'asdf'} = test_group_metadata GROUP\n.meta
tiledb/tests/test_group.py:153: AssertionError
```
due to fragment timestamp overlap.
=> Fix group metadata test sequencing

.github/workflows/ci.yml, .github/workflows/daily-test-build-numpy.yml, .github/workflows/daily-test-build.yml, misc/azure-ci.yml, setup.py
- Microsoft is currently issuing brownouts for macOS 10.15. Support in GitHub Actions will cease at the end of August and in Azure at the end of September. Our minimum supported version will need to be bumped to macOS 11 Big Sur.
=> [2.12] Migrate CI To Run On macOS 11.0

HISTORY.md, tiledb/core.cc, tiledb/query_condition.py, tiledb/tests/test_query_condition.py
For example,
```
qc = tiledb.QueryCondition("U < 3")
u_result = A.query(attr_cond=qc, attrs=["I"])[:]
```
The query condition is applied to `U` but we no longer have to pass `attrs=["U"]`.
=> Do Not Require Attribute in Query Condition To Be Passed to Query

HISTORY.md, tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
Context:
* Forward-porting https://github.com/single-cell-data/TileDB-SOMA/pull/273 from the `main-old` branch of `tiledbsoma-py` to the `main` branch.
* On `main-old` all the dataframes are written using `from_pandas`: e.g. https://github.com/single-cell-data/TileDB-SOMA/blob/0.1.12/apis/python/src/tiledbsoma/annotation_dataframe.py#L411-L425
* On `main` dataframes can be created that way, or from Arrow as at https://github.com/single-cell-data/TileDB-SOMA/blob/53af1a7a26dd241013102e9ac5b7db9e6a128393/apis/python/src/tiledbsoma/soma_dataframe.py#L92-L108
* When I use `dtype="ascii"` as on https://github.com/single-cell-data/TileDB-SOMA/pull/273, but in this non-from-pandas context (see https://github.com/single-cell-data/TileDB-SOMA/pull/359), I get
```
#!/usr/bin/env python
import …
```
=> Permit true-ASCII attributes in non-from-pandas dataframes

tiledb/dataframe_.py
Proof of working: https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=26689&view=logs&j=7911d560-0f89-5712-632b-f37e97582f1d
=> Fix `cannot import name 'TileDBError' from 'tiledb'` For Wheel Build on macOS

HISTORY.md, tiledb/npbuffer.cc, tiledb/tests/test_libtiledb.py
Previously, the following NumPy array would yield the data and offset buffers below.
```
>>> tiledb.main.array_to_buffer(np.array(["", "", "", "a", "", "", "", "", "", "b"], dtype=np.unicode_), True, False)
(array([97, 98,  0,  0,  0,  0,  0,  0,  0,  0], dtype=uint8), array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1], dtype=uint64))
```
The data buffer needs to be resized such that it does not containing the trailing NULLs. Otherwise, when we read the data back, we see the last element padded with trailing NULLs.
This PR now correctly yields the following data buffer.
```
>>> tiledb.main.array_to_buffer(np.array(["", "", "", "a", "", "", "", "", "", "b"], dtype=np.unicode_), True, False)
(array([97, 98], dtype=uint8), array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1], dtype=uint64)
```
=> `tiledb.main.array_to_buffer` Correct Data Buffer With Empty Strings

HISTORY.md, setup.py, tiledb/core.cc, tiledb/fragment.cc, tiledb/npbuffer.cc, tiledb/query_condition.cc, tiledb/schema_evolution.cc, tiledb/serialization.cc, tiledb/tests/test_schema_evolution.py, tiledb/util.cc, tiledb/util.h
* Replaces `throw_tiledb_error()` and `_throw_ctx_err()` that was previously in `schema_evolution.cc`
=> Addition of Utility Function `get_last_ctx_err_str()` for C API

HISTORY.md, setup.py, tiledb/core.cc, tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/multirange_indexing.py, tiledb/query_condition.py, tiledb/tests/test_multi_index.py, tiledb/tests/test_query_condition.py
* Deprecate `attr_cond` in favor of `cond`
* Allow `cond` to take in a string directly instead of using `tiledb.QueryCondition`
* Add `dim()` cast that behaves similarly to `attr()` but specifically for dimensions
* Add tests for overlapping ranges
=> Add Support For `QueryCondition` on Sparse Dimensions

HISTORY.md, tiledb/cc/enum.cc, tiledb/group.py, tiledb/libmetadata.pyx, tiledb/libtiledb.pxd, tiledb/tests/test_group.py, tiledb/tests/test_metadata.py
* Addition of `.dump()` functions to output information about metadata
=> Array and Group Metadata Store Bytes as `TILEDB_BLOB`

HISTORY.md, tiledb/fragment.py, tiledb/highlevel.py, tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/tests/test_fragments.py, tiledb/tests/test_libtiledb.py, tiledb/vfs.py
Example usage:
```
with tiledb.open(path, "m") as A:
A.delete_fragments(3, 6)
```
=> [2.12] Add Support For `Array.delete_fragments`

HISTORY.md, tiledb/cc/enum.cc, tiledb/core.cc, tiledb/highlevel.py, tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/tests/test_group.py, tiledb/tests/test_query_condition.py
Example usage:
```
with tiledb.open(path, "d") as A:
A.query(cond="attr < 4").submit()
```
* Delete data that satisfies a query condition
* Chery-picked relevant commit from https://github.com/TileDB-Inc/TileDB-Py/pull/1309
=> Support Query Deletes on Sparse Arrays

tiledb/tests/test_vfs.py, tiledb/vfs.py
The readinto is needed for a complete implemention of the `io.RawIOBase` interface.
=> Add support for readinto in FileIO

HISTORY.md, tiledb/query_condition.py, tiledb/tests/test_query_condition.py
- Wrap the query condition in parenthesis prior to parsing with AST to support multi-line continuation and whitespace padding that would be valid in Python if-cond statements
=> Fix Whitespace Handling in Query Conditions

.github/workflows/daily-test-build.yml
* Fix for #1418
* Explicitly use Python 3.10. Otherwise, default is now to use Python 3.11 which we (and PyArrow) do not yet fully support.
=> Explicitly Use Python 3.10 For Nightly Builds

HISTORY.md, tiledb/core.cc, tiledb/query_condition.py, tiledb/tests/test_query_condition.py
When using query conditions with `.df` and `.multi_index`, the attribute that was applied in condition would be returned in the result regardless of what was passed to the `attr` argument.
For example,
```
with open.tiledb(uri, "r") as A:
cond = "att < 10"
result = A.query(cond=cond, attr=[])[:]
assert "att" not in result 
result = A.query(cond=cond, attr=[]).df[:]
assert "att" not in result
```
=> Fix `.df` and `.multi_index` Returning Attrs Used In Query Condition

misc/azure-release.yml
* This was only disabled for failed builds previously as it would unnecessarily open issues for failed releases
* Sending a dispatch for succeeded builds will attempt to delete the nightly build branch. But the nightly build branch does not exist if this is a regular release
=> Do Not Dispatch Success Builds For Azure Nightly Builds

HISTORY.md, tiledb/multirange_indexing.py, tiledb/tests/test_pandas_dataframe.py
* Workaround PyArrow's `Table.to_pandas` converting all nullable integers to float64 type
=> Fix Nullable Integers in `df` when using PyArrow Path

HISTORY.md, tiledb/libtiledb.pyx, tiledb/query_condition.py, tiledb/tests/test_query_condition.py
- Blocked by https://github.com/TileDB-Inc/TileDB/pull/3651
=> [2.13] Support Boolean for Query Conditions

.github/workflows/ci.yml, .github/workflows/daily-test-build-numpy.yml, .github/workflows/daily-test-build.yml, HISTORY.md, examples/query_condition_dense.py, examples/query_condition_sparse.py, examples/query_condition_string.py, examples/vfs.py, misc/azure-ci.yml, misc/azure-release.yml, misc/pypi_linux/build.sh, misc/requirements_wheel.txt, requirements.txt, tiledb/libtiledb.pyx, tiledb/multirange_indexing.py, tiledb/tests/test_attribute.py, tiledb/tests/test_dask.py, tiledb/tests/test_query_condition.py, tiledb/tests/test_vfs.py, tiledb/vfs.py
* Support wheels for Python 3.11
* `DeprecationWarning`s for 0.19.0 now error out. These have been changed to `TileDBError`s. Error messages will be removed in two release cycles
=> Release 0.19.0 Against 2.13.0

misc/requirements_wheel.txt, requirements_dev.txt
* This was caught when building from source with Python 3.11 on macos was erroring out and the version of `setuptools` was found to be the culprit
* https://github.com/TileDB-Inc/TileDB-Py/issues/1493
=> Sync `setuptools` Pinning From `pyproject.toml` To `requirements_*.txt`

tiledb/filter.py, tiledb/tests/test_webp.py
Fixed by updating `filter.py` to remove use of `__capsule__` and `lt.Context`. Added some new unit tests to protect against this in the future. 
Also updated type of `input_format` to use the `WebpInputFormat` enum, but we still support setting input format using integral values and a test for this was also added in this PR.
=> Fix webp filter options

.github/workflows/ci.yml, .github/workflows/daily-test-build-numpy.yml, .github/workflows/daily-test-build.yml, misc/requirements_wheel.txt, pyproject.toml, requirements_dev.txt, setup.py
* On macOS with Python 3.11, using `python setup.py install` to build from source errors out. Replace with using `develop` instead
=> Install Using `python setup.py develop` In Tests

tiledb/cc/query.cc, tiledb/indexing.pyx, tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/tests/test_serialization.cc
Remove deprecated query C-API functions and replace them with the equivalent subarray C-API functions.
=> Use subarray API to set ranges

tiledb/fragment.cc, tiledb/tests/test_webp.py
* We now check to ensure NumPy array inputs match the dimensions in the
`ArraySchema` for dense writes as of https://github.com/TileDB-Inc/TileDB-Py/pull/1514
=> Modify `WebP` Test Inputs To Match Dims With `ArraySchema`

tiledb/libtiledb.pyx
During ingest of a mutli-GB dataset I found this error:
```
File "/home/ubuntu/git/single-cell-data/TileDB-SOMA/apis/python/src/tiledbsoma/annotation_dataframe.py", line 463, in from_dataframe
raise e
File "/home/ubuntu/git/single-cell-data/TileDB-SOMA/apis/python/src/tiledbsoma/annotation_dataframe.py", line 444, in from_dataframe
tiledb.from_pandas(
File "/home/ubuntu/git/TileDB-Inc/TileDB-Py/tiledb/dataframe_.py", line 451, in from_pandas
_from_pandas(uri, dataframe, tiledb_args)
File "/home/ubuntu/git/TileDB-Inc/TileDB-Py/tiledb/dataframe_.py", line 523, in _from_pandas
_write_array(
File "/home/ubuntu/git/TileDB-Inc/TileDB-Py/tiledb/dataframe_.py", line 607, in _write_array
libtiledb._setitem_impl_sparse(A, tuple(coords), write_dict, nullmaps)
File …
```
=> Allow discovery of non-ASCII dataframe attributes

tiledb/tests/test_metadata.py
* This should have been reverted before merging https://github.com/TileDB-Inc/TileDB-Py/pull/1327, but I forgot to modify
=> Remove Timing Check for `Metadata.test_basic`

HISTORY.md, tiledb/attribute.py, tiledb/dimension.py, tiledb/filter.py, tiledb/tests/test_dimension.py
* This fixes a larger scale issue that was originally caught in the SOMA unit tests https://github.com/single-cell-data/TileDB-SOMA/pull/653
* When the parent Pybind11 constructor fails, Pytest prints a backtrace of all the arguments in `super().__init__()` which includes the `self` object. Since the object does not exist, using the Pybind11 wrapped properties, namely `_filters`, results in a segfault
* We use `self._ctx`, which is a property that only exists on the pure Python object, to check if the object has been properly instantiated
=> Use Safe `repr` If Parent Pybind11 Constructor Fails

tiledb/core.cc, tiledb/libtiledb.pyx, tiledb/tests/test_fixes.py
Use a subarray to add ranges in PyQuery instead of deprecated `Query::add_range` calls.
=> Use subarray to set ranges in PyQuery

tiledb/tests/test_fixes.py
[ci skip] until other side merged in libtiledb.
=> Add test for SC-23827: default override w/ AWS_{DEFAULT_}REGION

tiledb/attribute.py, tiledb/ctx.py, tiledb/dimension.py, tiledb/domain.py, tiledb/filter.py, tiledb/libtiledb.pyx
Replace "private" constructor parameters (`_capsule`, `_lt_obv`) with `CtxMixin` classmethods (`from_capsule`, `from_pybind11`).Follow-up to https://github.com/TileDB-Inc/TileDB-Py/pull/1548.
=> CtxMixin classmethods

HISTORY.md, tiledb/attribute.py, tiledb/cc/common.cc, tiledb/tests/test_attribute.py, tiledb/tests/test_query_condition.py
- Correct `Attr.fill` for UTF-8
- Add unit tests for UTF-8 query conditions on dense arrays
=> Fix `Attr.fill` for UTF-8; add tests for UTF-8 Query Condition on dense arrays

tiledb/libmetadata.pyx, tiledb/libtiledb.pxd, tiledb/libtiledb.pyx
* Set encryption key in config
* Use `tiledb_array_set_open_timestamp_start` to set timestamp
* `tiledb_array_consolidate_metadata_with_key` --> `tiledb_array_consolidate_with_key`
* `tiledb_array_reopen_at` -> `tiledb_array_reopen`
=> Replace Deprecated libtiledb Array Open Functions

tiledb/tests/test_examples.py
=> Fix query_condition_datetime example when pandas not available

misc/azure-libtiledb-darwin.yml, misc/azure-release.yml
Adds support for building macOS arm64 wheels for CPython 3.8-3.11.
=> Add release builder support for macOS-arm64 wheels

.readthedocs.yml
RTD `build.os` config option requires setting `build.tools` simultaneously.
=> Also set ReadTheDocs build.tools

examples/quickstart_dimension_labels.py, tiledb/array_schema.py, tiledb/cc/dimension_label.cc, tiledb/cc/schema.cc, tiledb/data_order.py, tiledb/dimension.py, tiledb/dimension_label.py, tiledb/dimension_label_schema.py, tiledb/libtiledb.pyx, tiledb/multirange_indexing.py, tiledb/tests/test_dimension_label.py, tiledb/tests/test_query.py, tiledb/tests/test_subarray.py
Improve `DimLabel` class API:
* Add `order` property to `DimLabel` and use in repr functions
* Remove `label_` prefix from dtype, isvar, and isascii
* Remove URI form repr functions
Improve `DimLabelSchema` class:
* Remove `dim_index` from `DimLabelSchema`
* Add factory method to create `DimLabelSchema` from a `Dim`
Changes to `ArraySchema` class:
* Change `dim_labels` input to be a dict of dict over dimension index and dim label name
=> Dimension label API refinement

HISTORY.md, misc/azure-release.yml
Also fix macOS-arm64 libtiledb version (closes sc-26307).
=> Release 0.21.1 against TileDB 2.15.0

tiledb/__init__.py
Someone *cough* accidentally deleted the `__version__` string variable when they refactored the way setuptools-scm handled versions. This brings it back while also subjecting the reader to the word “version” enough to reach semantic satiation.
=> Restore `__version__` variable.

setup.py, tiledb/cc/group.cc, tiledb/group.py, tiledb/tests/test_group.py
* Add `config` parameter to `Group` constructor and `set_config` to the high-level `Group` API. This will help relieve the excessive allocation of `Ctx` objects in the TileDB-SOMA-Py codebase as described in https://github.com/single-cell-data/TileDB-SOMA/issues/1169)
* Group unit tests now use timestamps instead of `time.sleep()`
=> Addition of `Group(config=...)` and `Group.set_config`

tiledb/array_schema.py, tiledb/tests/test_fixes.py
Restores prior behavior changed in https://github.com/TileDB-Inc/TileDB-Py/pull/1609.
=> Fix sc-27374: default order mapping fallback

HISTORY.md, misc/azure-release.yml, setup.py
```
In [9]: tiledb.version(), tiledb.libtiledb.version()
Out[9]: ((0, 21, 4), (2, 15, 3))
```
=> Release 0.21.4 against TileDB 2.15.3

tiledb/libtiledb.pyx, tiledb/tests/test_query_condition.py
This treats an empty string `""` the same as None when applying a query condition. This is useful as users are passing strings for query condition and avoids the user needing to validate they've successfully built a condition before passing it in.
=> Handle empty string passed to Query condition

tiledb/cc/group.cc
Failing to do overload resolution in pybind11.
=> Fix group.close to work on 2.16

tiledb/array_schema.py
Raised by @bkmartinjr on Slack -- it needs to be clearer what version this is. Also, we have a typo.
=> Fix an online-help typo, and clarify

tiledb/array_schema.py
Capacity is not applicable to dense arrays and has no effect, so we should not print it out.
=> Only sparse arrays should print capacity in repr

.github/workflows/daily-test-build-issue-template.md, .github/workflows/daily-test-build-numpy.yml, .github/workflows/daily-test-build.yml, .github/workflows/issue-if-azure-fail-template.md, .github/workflows/issue-if-azure-fail.yml
This PR updates all the nightly GitHub Actions workflows to append to an existing open Issue instead of always creating a new one.
The action [JasonEtco/create-an-issue](https://github.com/JasonEtco/create-an-issue) requires that the existing open Issue has the [exact same title](https://github.com/JasonEtco/create-an-issue/blob/main/action.yml#L20):
>  Update an open existing issue with the same title if it exists
I haven't tested this on my fork yet. If you approve of the strategy, I'll generate some spurious build errors on my fork to confirm it works as expected.
If you'd prefer to adopt this appending behavior but still keep the date of the initial build failure in the Issue title, we could switch to using the `gh` cli approach I have used in the past (eg [in …
=> Append nightly failure updates if an open Issue exists

tiledb/libtiledb.pyx
* When running tests locally, the example array gets created but does not get deleted. This results in  subsequent test runs erroring out because it tries to create the array again, but it already exists.
=> Use Tmp Dir in Docs Example For Dim Labels

tiledb/tests/test_vfs.py, tiledb/vfs.py
When working on a change in tiledbsoma [1], we ran into somewhat mysterious error messages where things had worked before. This was because, unlike `open` (and other libraries which accept path-likes), `tiledb.VFS` only accepts `str` (and undocumented `bytes`) paths. Accepting path-like objects (like `pathlib.Path`s) lets us play better with other libraries and user code.
[1]: https://github.com/single-cell-data/TileDB-SOMA/pull/1629
=> Make VFS accept path-like objects to refer to files.

.github/disabled-workflows/release.yml, .github/workflows/ci.yml, .github/workflows/daily-test-build-issue-template.md, .github/workflows/daily-test-build-numpy.yml, .github/workflows/daily-test-build.yml, .github/workflows/format.yml, .github/workflows/issue-if-azure-fail-template.md, .github/workflows/issue-if-azure-fail.yml
Follow up to https://github.com/TileDB-Inc/TileDB-Py/pull/1813. The new GitHub action [open-issue](https://github.com/TileDB-Inc/github-actions/tree/main/open-issue) comments on existing open Issues, instead of overwriting like the current action.
Before merging, someone with admin access to this repo needs to:
cc: @ihnorton, @nguyenv 
xref: https://github.com/TileDB-Inc/github-actions/pull/4, https://github.com/TileDB-Inc/TileDB-Py/issues/1817
=> Switch to TileDB-Inc/github-actions/open-issue

tiledb/npbuffer.cc, tiledb/tests/test_dask.py, tiledb/tests/test_hypothesis.py, tiledb/tests/test_multi_index-hp.py
The test here fails when run with dask distributed. The array is passed through dask serialization, and the buffer conversion fails because the dtype object in the npbuffer.cc line modified here returns False. This is because the array's dtype is not === to the dtype("O") object in the parent process after serialization.
=> Use object equality check in buffer conversion; fixes sc-33742

tiledb/multirange_indexing.py, tiledb/tests/test_basic_import.py
Importing Pandas takes a significant amount of time; nearly half a second in UDFs. Previously, we imported it eagerly if it was present, even though outside of a couple functions it was only used for type annotations. This change ensures that we only import it exactly when we actually use it.
=> Avoid importing Pandas until we actually use it.

tiledb/dataframe_.py, tiledb/tests/test_pandas_dataframe.py
This adds support in from_pandas for converting and handling categorical datatypes.
Notes: There are some deficiencies in pandas pre-2.0, namely they do not store a dtype of the enumeration/categorical values. Instead they are always treated as an object array. As such we need to infer the type and this has limitations, such as being able to easily detect signed vs unsigned integers without manually checking all values. This PR takes a first-pass best effort at dtype conversion for the pandas categorical values. Future PRs are likely to improve this.
Example usage:
```
df = pd.DataFrame(
{
"int": [0, 1, 2, 3],
"categorical_string": pd.Series(["A", "B", "A", "B"], dtype="category"),
"categorical_int": pd.Series(
np.array([1, 2, 3, 4], dtype=np.int8), dtype="category"
),
}
) …
```
=> Support categoricals in from_pandas

tiledb/libtiledb.pyx, tiledb/npbuffer.cc, tiledb/tests/test_query_condition.py
This fixes https://github.com/TileDB-Inc/TileDB-Py/issues/1730
=> Fix "unexpected object type in string conversion" error when using booleans

tiledb/schema_evolution.py, tiledb/tests/test_schema_evolution.py
This PR adds `SchemaEvolution.add_enumeration` and `SchemaEvolution.drop_enumeration`. The bindings were done in a previous PR but never added to `SchemaEvolution`.
=> Add Support For `SchemaEvolution` on Enumerations

tiledb/core.cc, tiledb/libtiledb.pyx, tiledb/tests/test_enumeration.py, tiledb/tests/test_libtiledb.py
**Background**
As detailed in sc-34754, this fixes a bug found by a customer using the TileDB-SOMA Python API where the `SOMADataFrame` containing an enumerated nullable attribute was not being readback correctly. This highlights a larger deficit in the TileDB-Py codebase in which we have [little support](https://docs.tiledb.com/main/how-to/arrays/writing-arrays/nullable-attributes) for writing nullable attributes outside of utilizing `tiledb.from_pandas` with Pandas's `ExtensionDtype`.
**Changes**
- This PR supports writing Pyarrow arrays and Pandas dataframes that contain nullable values (`pd.NA`, `pa.na`, `None`, etc.). 
- Nullable attributes are now represented in Numpy as [masked arrays](https://numpy.org/doc/stable/reference/maskedarray.html). 
- `PyQuery` results now also return …
=> Additional Support For Nullable Attributes

tiledb/tests/test_schema_evolution.py
After the array has been evolved, the schema evolution operation is now considered complete, and a new `ArraySchemaEvolution` object needs to be created prior to running another schema evolution.
=> Create `ArraySchemaEvolution` For New Operation

tiledb/query_condition.cc, tiledb/query_condition.py, tiledb/tests/test_query_condition.py
* Switch out the old set membership internal code with new faster method in core
* No visible changes to the user
TODO
=> Support New Set Membership Query Condition

HISTORY.md, misc/azure-release.yml
Wheel test: https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=35977&view=results
```
In [1]: import tiledb
tiledb.ver
In [2]: tiledb.version(), tiledb.libtiledb.version()
Out[2]: ((0, 23, 2), (2, 17, 3))
```
=> Update HISTORY for 0.23.2

HISTORY.md, tiledb/multirange_indexing.py
* Pandas 2.0 has deprecated many functions including passing the metadata as an argument to the `pa.schema` constructor. This has been replaced with a separate call to `with_metadata`
=> Use `with_metadata` instead of argument to `pa.schema` constructor

HISTORY.md, tiledb/enumeration.py, tiledb/multirange_indexing.py
Finding:
```
>>> np.issubdtype(np.asarray([1,2,3],dtype=np.int32).dtype, np.integer)
True
>>> np.issubdtype(np.asarray([1,2,3],dtype=np.uint32).dtype, np.integer)
True
>>> np.issubdtype(np.asarray([1,2,3],dtype=np.int32).dtype.kind, np.integer)
True
>>> np.issubdtype(np.asarray([1,2,3],dtype=np.uint32).dtype.kind, np.integer)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/numerictypes.py", line 416, in issubdtype
arg1 = dtype(arg1).type
TypeError: data type 'u' not understood
```
So we should just do the first two, not the second two.
Found by @bkmartinjr in a TileDB-SOMA context: https://gist.github.com/johnkerl/3beaf565041a4acdbd534cba0e53bdae
I'll turn that gist into a …
=> Work around NumPy issue with `dtype.kind` of unsigned ints

tiledb/enumeration.py, tiledb/tests/test_enumeration.py, tiledb/tests/test_schema_evolution.py
For empty enumerations, since we did not explicitly cast the empty numpy array, it was automatically casted to a dtype of float64
=> Cast enum values to enum dtype

tiledb/filter.py, tiledb/tests/test_filters.py
This returns the underlying TileDB string name for the filter types.
=> Add `filter_name` to Filter class

tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
* `np.nan_to_num` cannot be used on string arrays
* We should hold off on merging this PR until we get https://github.com/single-cell-data/TileDB-SOMA/pull/1834 passing, and the confirm that [this](https://github.com/TileDB-Inc/TileDB-Py/pull/1848#issuecomment-1781413424) repro script passes
=> Correct Nullable String Attributes and All NULL Data

tiledb/vfs.py
The Core does the flushing by itself if needed.
https://github.com/TileDB-Inc/TileDB/blob/5efd7f53df6646c3b5894b0f7b06e1314f68c214/tiledb/sm/filesystem/vfs_file_handle.cc#L69-L70
https://github.com/TileDB-Inc/TileDB/blob/5efd7f53df6646c3b5894b0f7b06e1314f68c214/tiledb/sm/filesystem/vfs.cc#L1455-L1462
=> Do not flush VFS files on closing.

tiledb/cc/filter.cc, tiledb/filter.py, tiledb/tests/test_filters.py
The option for reinterpret datatype was not being copied back into the DeltaFilter and DoubleDeltaFilter when accessing them as part of the FilterList. This only affected the Python layer. The C++ backend for the filters still had the full options set.
=> Fix reading DeltaFilter and DoubleDeltaFilter options for FilterList

tiledb/dimension.py, tiledb/domain.py, tiledb/tests/test_dimension.py, tiledb/tests/test_domain.py, tiledb/tests/test_libtiledb.py
Fixes:
* Add checks for matching filters and variable length in `Dim.__eq__`.
* Fix bug where error is thrown when using `Domain.__eq__` on a non-integral sparse domain.
* Fix bug where filters are dropped from dimensions in a domain with all anonymous dimensions.
=> Fix domain equality check

tiledb/tests/test_group.py
Reported in internal channel: https://tiledb.slack.com/archives/C052CFC4D2Q/p1701187714576329
=> Skip `test_consolidation_and_vac_no_config` For libtiledb < 2.18.0

tiledb/dataframe_.py, tiledb/tests/test_enumeration.py
Fixes issue #1879 for Python
As reported by @atolopko-czi
=> Use enum in `ArraySchema` for to-be-written Pandas category

HISTORY.md, tiledb/group.py, tiledb/tests/test_group.py
See https://github.com/TileDB-Inc/TileDB-Py/pull/1545/ for a full explanation. This just needed to be added for the `Group` class as well.
=> Safe repr for `Group`

pyproject.toml, tiledb/tests/test_pandas_dataframe.py
- ~I would like to just add a `pytest.ini` file to silence `DeprecationWarnings` that emit the message `Passing a BlockManager to DataFrame is deprecated`. This seems to somewhat work as tests are now passing but seems to skip entire test files which is not what I intended. I would like the tests to run, allow PyArrow to emit the warning, but silence them when testing.~
- `pytest.ini` was overriding options already set in `pyproject.toml`
=> Ignore `DeprecationWarning` Emitted From pyarrow/pandas

tiledb/tests/test_multi_index-hp.py
These two tests occasionally cause spurious nightly failures because one instance takes longer than the deadline of 200ms, causing it to fail. For a recent example, see https://github.com/TileDB-Inc/conda-forge-nightly-controller/issues/43#issuecomment-1915011772
I followed the [examples of the other flaky tests](https://github.com/search?q=repo%3ATileDB-Inc%2FTileDB-Py%20deadline&type=code) to remove the deadline
=> Remove deadline for two flaky tests

tiledb/array_schema.py, tiledb/attribute.py, tiledb/dimension.py, tiledb/domain.py, tiledb/enumeration.py, tiledb/filter.py, tiledb/group.py, tiledb/tests/test_array_schema.py
- We cannot rely solely on checking if the context exists for the `ArraySchema`. We call the parent `lt.ArraySchema` constructor at the beginning of `__init__` which does set a valid context and creates the Pybind11 object. Then we set the other schema properties onto that object. If any of the other properties the user passed in are invalid (like the `cell_order` or `tile_order`), then simply checking the existence of a context does not work. Fortunately with the `ArraySchema`, there is an `lt.ArraySchema._check` to ensure if it a properly constructor schema
- I am not sure what happened, but the safe reprs which were added in https://github.com/TileDB-Inc/TileDB-Py/pull/1545 all disappeared. I'm assuming a PR was not merged correctly after #1545, but they have now been restored
=> Use safe repr if `ArraySchema` was not properly constructed

tiledb/cc/attribute.cc, tiledb/cc/context.cc, tiledb/cc/dimension_label.cc, tiledb/cc/domain.cc, tiledb/cc/enumeration.cc, tiledb/cc/filter.cc, tiledb/cc/schema.cc, tiledb/cc/subarray.cc, tiledb/query_condition.cc
I got multiple errors like this:
```error: call of overloaded ‘capsule(std::__shared_ptr<tiledb_subarray_t, __gnu_cxx::_S_atomic>::element_type*, const char [9], std::nullptr_t)’ is ambiguous```
when building fresh with latest pybind on ubuntu22, `m6id.4xlarge` ec2 machine.
Not sure this is the correct fix, just fixed all the errors to get myself a successful build and thought effort shouldn't go to waste in case it's the correct approach.
=> Fix ambiguous capsule calls with pybind11

misc/azure-release.yml
GCS currently disabled in PyPI wheels, this PR enables.
x-ref https://github.com/TileDB-Inc/TileDB-Py/issues/1262#issuecomment-1937329349
=> Enable GCS in osx-arm64 release build

misc/requirements_wheel.txt, pyproject.toml, requirements_dev.txt
Unblock the conda-forge migration to Python 3.12
xref: https://github.com/conda-forge/tiledb-py-feedstock/pull/199#issuecomment-1954502654, https://github.com/TileDB-Inc/TileDB-Py/pull/1805, https://github.com/TileDB-Inc/TileDB-Py/commit/d7d7019ea713b6bb56fbf2460920896f94952846
=> Remove upper bound on pybind11

examples/in_memory_vfs.py
Add an example of how to use new in-memory URI base **mem://** for TileDB VFS operations, provided by backend.
=> Add mem:// backend example

tiledb/tests/test_pandas_dataframe.py
The `tiledb.from_csv` and `tiledb.from_pandas` functions have been causing intermittent errors when running the unit tests with the message:
```
UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
```
Example failure: https://github.com/TileDB-Inc/TileDB-Py/actions/runs/7911328196/job/21595351207#step:10:1029
This is solved by explicitly passing `date_format` argument into each `from_{csv,pandas}` call.
Please note that the `date_format` argument is not available for Python 3.7 and below, so tests containing it should be skipped.
=> Specify datetime format in tests

tiledb/filestore.py, tiledb/tests/test_filestore.py
In `Filestore` class, in the `read()` method this line `size = max(size - offset, 0)` does not cover the case of trying to read a size that is smaller than the offset. Consider a 4 byte file. If we want to read the last byte (offset 3, size 1) this check sets the size to 0 incorrectly.
Changing it to `size = min(size, len(self) - offset)` ensures that we read either the specified size or the remaining length of the file store starting from the offset, whichever is smaller.
=> Fix Filestore unable to read sizes smaller than offset

HISTORY.md, misc/azure-release.yml
Update HISTORY and version for 0.26.2
=> Update HISTORY and version for 0.26.2

tiledb/tests/test_vfs.py, tiledb/vfs.py
Trying to ingest an Hamamatsu CMU-1.ndpi https://openslide.cs.cmu.edu/download/openslide-testdata/Hamamatsu/ image using `tiledb.bioimg`:
```
from tiledb.bioimg import from_bioimg
import tiledb
vfs = tiledb.VFS()
with vfs.open('CMU-1.ndpi') as src:
from_bioimg(src, "test_bioimg")
```
was giving the following error:
```
File "/Users/agis/tiledb_dev/TileDB-BioImaging/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "&lt;ipython-input-5-f900874cbef5&gt;", line 2, in &lt;module&gt;
from_bioimg(src, "/Users/agis/tiledb_dev/TileDB-BioImaging/tests/data/cmu1_failed_v2.ndpi.tdb")
File "/Users/agis/tiledb_dev/TileDB-BioImaging/tiledb/bioimg/wrappers.py", line 35, in from_bioimg
return …
```
=> Fix vfs readinto when buff is not bytes

.github/workflows/ci.yml, .github/workflows/daily-test-build-numpy.yml, misc/azure-release.yml
Removing Python 3.7 CI jobs from all GitHub workflows.
=> Remove Python 3.7 CI jobs

HISTORY.md, misc/azure-release.yml
Update HISTORY for 0.26.3 against TileDB 2.20
=> Update HISTORY for 0.26.3 against TileDB 2.20

pyproject.toml, setup.py, tiledb/vfs.py
Fixes readinto() description for the docs and moves more metadata into pyproject.toml.
=> Minor fix docs

requirements_dev.txt
Requirements such as `pandas` are missing when trying to run `pytest`, even after running `pip install -r requirements_dev.txt`, leading to skipped tests. This fixes it.
=> Fix missing dev requirements

misc/requirements_wheel.txt, pyproject.toml, requirements_dev.txt, tiledb/libtiledb.pxd, tiledb/libtiledb.pyx
Fix build with Cython 3 - it no longer adds implicit noexcept to callbacks
=> Fix build with Cython 3 - it no longer adds implicit noexcept to callbacks

pyproject.toml
- How I tested it:
```
pipx run build
unzip -l dist/tiledb-0.26.4.dev4-cp312-cp312-macosx_14_0_arm64.whl | grep '\.pyc$'
tar -tzf dist/tiledb-0.26.4.dev4.tar.gz | grep '\.pyc$'
pipx run build --sdist
tar -tzf dist/tiledb-0.26.4.dev5.tar.gz | grep '\.pyc$'
```
They all return nothing.
- A change that has to be done was not to append the local version identifier to the version number. This approach ensures cleaner version numbers that rely solely on tags, without incorporating any local version data. Consequently, versions generated during the CI build will be compatible with PyPI. Previously, a 'dirty-tag' was being used: https://github.com/TileDB-Inc/TileDB-Py/blob/0b14a6eb623fc2a2c202c3da6e638e9a3668925a/setup.py#L796 resulting in errors like this when running `pipx run build`.
```
CMake …
```
=> Don't package .pyc files in wheels and generate PyPi compatible version number

tiledb/tests/test_vfs.py, tiledb/vfs.py
Fix read, seek with numpy integer sizes
=> Fix read, seek with numpy integer sizes

HISTORY.md, misc/azure-release.yml
Update HISTORY for 0.26.4 against TileDB 2.20.1
=> Update HISTORY for 0.26.4 against TileDB 2.20.1

setup.py, tiledb/tests/test_query_condition.py
https://github.com/TileDB-Inc/TileDB-Py/issues/1880
This is now fixed in core. This PR just adds unit tests to ensure query conditions return an empty result, instead of erroring out, for invalid enumeration values.
=> [2.21.0] Add tests to ensure empty result on query condition for invalid enum

pyproject.toml
Tested using:
```
pipx run build
tar -tzf dist/tiledb-0.27.1.dev2.tar.gz | grep -E '(\.pytest_cache|\.hypothesis)'\n
unzip -l dist/tiledb-0.27.1.dev2-cp312-cp312-macosx_14_0_arm64.whl | grep -E '(\.pytest_cache|\.hypothesis)'\n
```
They both return nothing.
=> Exclude .pytest_cache and .hypothesis files

setup.py, tiledb/indexing.pyx, tiledb/libmetadata.pyx, tiledb/libtiledb.pxd, tiledb/libtiledb.pyx
Removes the `--modular` option when building TileDB-Py.
=> Remove modular building option

tiledb/tests/test_group.py
Checks for cases where the `uri` passed in the constructor is not of type `Group`.
=> Add test for Group constructor invalid uri object type

tiledb/libtiledb.pyx
Update doc string for `fragment_uris` parameter of `tiledb.consolidate`, fixes https://github.com/TileDB-Inc/TileDB-Py/issues/1944
=> Update doc for tiledb.consolidate

HISTORY.md, misc/azure-release.yml, setup.py
TileDB-Py 0.28.0 against TileDB 2.22.0
---
wheel test build on this branch: https://github.com/TileDB-Inc/TileDB-Py/pull/new/release-test-0.28.0-2.22.0
=> TileDB-Py 0.28.0 against TileDB 2.22.0

.github/workflows/ci.yml, setup.py, tiledb/tests/test_fixes.py, tiledb/tests/test_fragments.py, tiledb/tests/test_group.py, tiledb/tests/test_libtiledb.py, tiledb/tests/test_metadata.py, tiledb/tests/test_query_condition.py, tiledb/tests/test_timestamp_overrides.py
Currently in TileDB-Py we have a number of tests which override the timestamp for writes in order to avoid test failures when writes happen within the same millisecond, e.g.:
https://github.com/TileDB-Inc/TileDB-Py/blob/ff2149738a5daeee2c11d7660b3c7631fe1a293e/tiledb/tests/cc/test_cc.py#L124
https://github.com/TileDB-Inc/TileDB-Py/blob/ff2149738a5daeee2c11d7660b3c7631fe1a293e/tiledb/tests/test_fragments.py#L100
In libtiledb [2.22.0](https://github.com/TileDB-Inc/TileDB/releases/tag/2.22.0) a sub-millisecond temporal disambiguation of random labels from a single-process is implemented (serialized ordering for writes).
To test this from Python, tests that use timestamp ordering overrides are modified. They now run both with and without overriding and they should succeed in both cases. This …
=> Make timestamp overrides optional in tests and add faketime test

tiledb/cc/context.cc, tiledb/tests/test_context_and_config.py
Iterating over the config takes a prefix to filter the config parameters on. This was accidently broken in the pybind11 migration. This restores the functionality.
Before:
```
>>> import tiledb
>>> cfg = tiledb.Config()
>>> list(cfg.keys("sm."))
['config.env_var_prefix', 'config.logging_format', 'config.logging_level', 'filestore.buffer_size', 'rest.capnp_traversal_limit', 'rest.curl.buffer_size', 'rest.curl.verbose', 'rest.http_compressor', 'rest.load_enumerations_on_array_open', 'rest.load_metadata_on_array_open', 'rest.load_non_empty_domain_on_array_open', 'rest.retry_count', 'rest.retry_delay_factor', 'rest.retry_http_codes', 'rest.retry_initial_delay_ms', 'rest.server_address', 'rest.server_serialization_format', 'rest.use_refactored_array_open', …
```
=> Pybin11 Config should honor prefix for iter

tiledb/libmetadata.pyx, tiledb/libtiledb.pxd, tiledb/libtiledb.pyx, tiledb/tests/test_fragments.py, tiledb/tests/test_libtiledb.py
Python was using the following deprecated APIs:
- `tiledb_array_consolidate_with_key`
- `tiledb_array_create_with_key`
- `tiledb_array_delete_array`
- `tiledb_array_delete_fragments`
---
[sc-45876]
=> Migrate away from deprecated TileDB C++ APIs

setup.py, tiledb/cc/vfs.cc, tiledb/libtiledb.pxd, tiledb/tests/test_vfs.py, tiledb/vfs.py
- Add pybind11 wrapping for ls_recursive
- Connect to the high-level VFS.ls API as a keyword argument
- Test
=> Add wrapping for ls_recursive

HISTORY.md, misc/azure-release.yml, pyproject.toml, setup.py
=> Update HISTORY for TileDB-Py 0.29.0 against TileDB 2.23.0

HISTORY.md, tiledb/cc/vfs.cc, tiledb/libtiledb.pxd, tiledb/tests/test_vfs.py, tiledb/vfs.py
- Fixes problem building windows wheels. For reference the log can be found here: https://gist.github.com/kounelisagis/d250a5f2dd994a236a14e8493810c73e
The error is this part of the log:
```
tiledb/cc\vfs.cc(56): error C2039: 'VFSExperimental': is not a member of 'tiledb'
C:\include\tiledb\subarray_experimental.h(41): note: see declaration of 'tiledb'
tiledb/cc\[vfs.cc](http://vfs.cc/)(56): error C3083: 'VFSExperimental': the symbol to the left of a '::' must be a type
tiledb/cc\vfs.cc(56): error C2039: 'ls_recursive': is not a member of 'tiledb'
C:\include\tiledb\subarray_experimental.h(41): note: see declaration of 'tiledb'
tiledb/cc\[vfs.cc](http://vfs.cc/)(56): error C3861: 'ls_recursive': identifier not found
tiledb/cc\vfs.cc(65): error C2039: 'VFSExperimental': is not a member of …
```
=> Revert 1933 agis/sc 43316/add wrapping for ls recursive

pyproject.toml
Set an upper bound for numpy to dodge 2.0 and avoid incompatible upcoming release until we support it. x-ref sc-46950
=> Set an upper bound for numpy to dodge 2.0

tiledb/__init__.py, tiledb/fragment.py, tiledb/libtiledb.pyx
In #1958 the static method delete_fragments replaced the instance method with the same name. This, instead of deprecation warning, caused errors for vector search tests: https://github.com/TileDB-Inc/TileDB-Vector-Search/actions/runs/9060651237/job/24890783433?pr=369
In this PR:
- Since both methods have the same name and number of required arguments, it's impossible to have two separate methods in Python even after using the `@staticmethod` decorator. We use just one function, checking the argument type.
Both `tiledb.Array.delete_fragments(path, 2, 2)` and 
```
>>> with tiledb.open(path, 'm') as A:
...     A.delete_fragments(2, 2)
```
are now valid.
- A higher level `delete_fragments()` function is deleted. Should have been removed since `0.21.0`.
---
[sc-47282]
=> Compatibility fix: delete_fragments

.github/workflows/daily-test-build-numpy.yml, tiledb/tests/cc/test_cc.py
Fix syntax error in nightly build workflow
```
Nested mappings are not allowed in compact mappings at line 37, column 33:
MACOSX_DEPLOYMENT_TARGET: ${{ matrix.os == 'macos-12' && matrix.python-ve…
```
=> Fix syntax error in nightly build workflow

tiledb/filter.py, tiledb/tests/test_webp.py
Right now, the only way to access WebP enums is through `tiledb.cc` namespace. We need to expose them at the top level.
=> Expose WebP enums

tiledb/libtiledb.pyx, tiledb/tests/test_libtiledb.py
Incomplete queries are only supported for sparse arrays in TileDB-Py at this time. Dense reads will internally reallocate buffers and resubmit the query until successful completion. Docs: https://docs.tiledb.com/main/how-to/arrays/reading-arrays/incomplete-queries
Additionally, create a test to verify the expected behavior for both sparse and dense arrays.
=> Fix Query constructor to return error for dense arrays with return_incomplete=True

tiledb/filter.py
The provided example in the `CompressionFilter` class docstring incorrectly used `GzipFilter` instead of `CompressionFilter`. This PR fixes the issue, ensuring that the example accurately reflects the intended use of the base class for compression filters, rather than a specific filter type.
=> Fix CompressionFilter docstring example

HISTORY.md, pyproject.toml
The following error occurs when trying to build. Fixed by adding `numpy` in build dependencies.
```
File "/home/vsts/.local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in <module>
main()
File "/home/vsts/.local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 357, in main
json_out["return_val"] = hook(**hook_input["kwargs"])
File "/home/vsts/.local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 308, in get_requires_for_build_sdist
return hook(config_settings)
File "/tmp/build-env-dg88woc1/lib/python3.10/site-packages/setuptools/build_meta.py", line 328, in get_requires_for_build_sdist
return self._get_build_requires(config_settings, requirements=[])
File …
```
=> Fix ModuleNotFoundError: No module named 'numpy' on build

tiledb/libtiledb.pyx, tiledb/tests/test_fixes.py, tiledb/tests/test_libtiledb.py
Deprecate support for [] indexing with floats. NumPy no longer allows this (as of [1.12](https://numpy.org/devdocs/release/1.12.0-notes.html#deprecationwarning-to-error)), and it can cause confusion because of the wrap-around semantics.
=> Deprecate support for `[]` indexing with floats

tiledb/tests/test_attribute.py
Adds tests to ensure that `.dtype` and `.dump()` of `Attribute` class returns what expected.
=> Add tests for blob type attributes

.github/workflows/ci.yml, .github/workflows/daily-test-build-numpy.yml, .github/workflows/daily-test-build.yml
[SC-48973](https://app.shortcut.com/tiledb-inc/story/48973/revert-pins-to-msvc-toolset-14-39)
GitHub Actions is starting to update the MSVC toolset version in CI, causing [occasional failures](https://github.com/TileDB-Inc/TileDB-Py/actions/runs/9398673865/job/25888740034). This PR removes the pin to version 14.39 added in #1906.
=> Remove pin to MSVC toolset version in CI.

misc/requirements_wheel.txt, pyproject.toml, requirements.txt, requirements_dev.txt
Right now, there is no single source of truth for dependencies. Until this is done, let's fix the required versions of numpy found in multiple project files. There are basically 5 different places where numpy version requirements should be specified:
1. `requirements.txt`
2. `requirements_dev.txt`
3. `requirements_wheel.txt`
4. `pyproject.toml -> build-system -> requires`
5. `pyproject.toml -> project -> dependencies`
They can be merged into 3 categories:
- **build dependencies**: `pyproject.toml -> build-system -> requires` and `requirements_wheel.txt` are the requirements when building wheels (https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#build-system-requirement). For python 3.8 wheels have to be built against numpy `1.17` because we want support for …
=> Fix pinning wrong numpy version

tiledb/tests/test_vfs.py, tiledb/vfs.py
Following https://github.com/TileDB-Inc/TileDB/pull/4981 and https://github.com/TileDB-Inc/TileDB/pull/4997, this PR updates the docstring of `ls_recursive` and the skip condition for its test.
=> [2.24] Document Azure, GCS and local support for `VFS.ls_recursive`

.github/workflows/ci.yml, .github/workflows/daily-test-build-numpy.yml, .github/workflows/daily-test-build.yml, HISTORY.md, misc/azure-release.yml, misc/requirements_wheel.txt, pyproject.toml, requirements.txt, requirements_dev.txt
Cherry picks f580dc71d601575d5b61086f622a870884049206 and backports #1989 + adding upper bounds.
Solves downloading numpy 2.0.0 after the stable version was made available. numpy2 is supported for `TileDB-Py >= 0.30`.
=> [Backport release-0.29.1] Add numpy upper bound to dodge 2.0

tiledb/tests/test_dask.py
`test_sc33742_dask_array_object_dtype_conversion` is causing an error on windows CI. Let's skip it for windows as done with the other Dask test. We will investigate further the reason for failing in a later story.
---
[sc-49880]
=> Skip Dask test on Windows

HISTORY.md, misc/azure-release.yml, setup.py
Updates HISTORY for 0.30.1 against TileDB 2.24.1
Also updates HISTORY for backport 0.29.1 TileDB 2.23.0
=> Update HISTORY for 0.30.1 against TileDB 2.24.1

tiledb/dataframe_.py, tiledb/tests/test_pandas_dataframe.py
Adds offending column when `from_pandas` -> `_get_column_infos` fails.
e.g. `NotImplementedError: boolean inferred dtype not supported` becomes `NotImplementedError: boolean inferred dtype not supported (column foo)`.
=> Have `from_pandas` list offending column when `_get_column_infos` fails

tiledb/libtiledb.pyx, tiledb/tests/test_enumeration.py, tiledb/tests/test_libtiledb.py
This PR fixes `array.query()` incorrectly handling nullables. It was a logic issue.
When masking an array using `np.ma.array` with a mask derived from a subarray selection, as seen here: https://github.com/TileDB-Inc/TileDB-Py/blob/8c92a30bd3d2a5340c4498f48713f75d5813549d/tiledb/libtiledb.pyx#L3383, the mask should not be inverted because it's already a mask. Invertion is only needed when the array used originates from PyArrow::results, as shown here: https://github.com/TileDB-Inc/TileDB-Py/blob/8c92a30bd3d2a5340c4498f48713f75d5813549d/tiledb/core.cc#L1367. In that case it's the inverse of a mask.
---
A minimal reproducible example:
```
import tiledb
import numpy as np
import pyarrow as pa
import tempfile
uri = tempfile.mkdtemp()
schema = tiledb.ArraySchema( …
```
=> Fix `array.query()` incorrectly handling nullables

tiledb/__init__.py, tiledb/core.cc, tiledb/highlevel.py, tiledb/tests/test_libtiledb.py
- Wraps `as_built` function.
- Adds test
- Fixes disable_stats typo
The function was implemented with an optional argument `as_string=False`.
This is because it is easier for the user to use a dictionary structure rather than a string. When the argument is set to `True`, the function returns output identical to the C API.
=> Wrap as_built function

tiledb/libtiledb.pyx, tiledb/tests/test_fixes.py
The problem is related to https://numpy.org/neps/nep-0050-scalar-promotion.html#nep50.
Especially the fact that in numpy2 this behavior is not valid anymore:
```
>>> np.uint64(5) + -1
OverflowError: Python integer -1 out of bounds for uint64
```
And we have to do this:
```
>>> np.uint64(5) + np.int64(-1)
np.float64(4.0)
```
I had made a fix when support for `numpy2` was added, converting `start`,`stop`,`step` to `np.int64`, but this caused this overflow.
=> Fix OverflowError: Python int too large to convert to C long

tiledb/enumeration.py
Found while working with a customer
=> Fix a typo in an error message

.github/workflows/build-wheels.yml
Disable automatic upload until we release the first wheels with scikit-build-core
=> Temporarily disable upload to PyPI

examples/incomplete_iteration.py, examples/parallel_csv_ingestion.py, tiledb/dataframe_.py, tiledb/tests/common.py, tiledb/tests/test_enumeration.py, tiledb/tests/test_examples.py, tiledb/tests/test_fixes.py, tiledb/tests/test_hypothesis.py, tiledb/tests/test_libtiledb.py, tiledb/tests/test_multi_index.py, tiledb/tests/test_pandas_dataframe.py, tiledb/tests/test_query_condition.py
Pandas 3.0 is expected to release soon: https://pandas.pydata.org/docs/dev/whatsnew/v3.0.0.html
Since there are errors and deprecations when running tests with `pandas-3.0.0.dev0` (https://gist.github.com/kounelisagis/bb0b3896da4867882182b30c5224db5d) it would be wise to pin `pandas 2.x` until we add support for the new version.
Tests that require pandas, are skipped if `pandas 2.x` is not found, after this PR.
---
[sc-49618]
=> Add version pins for pandas 3.0

.github/workflows/build-wheels.yml
This way we can produce wheels with any version number:
From `workflow-dispatch` with input argument `123.1.7`:
https://github.com/dudoslav/TileDB-Py/actions/runs/10060209953/job/27807250342#step:3:24
From release triggered by creating tag `700.11.3`:
https://github.com/dudoslav/TileDB-Py/actions/runs/10060350710/job/27807753665#step:3:26
=> Set version in workflow dispatch

tiledb/cc/array.cc, tiledb/tests/test_pandas_dataframe.py
This PR fixes:
- API deprecation found in https://github.com/jdblischak/centralized-tiledb-nightlies/issues/14 and not fixed in https://github.com/TileDB-Inc/TileDB-Py/pull/1958
- code mistakenly deleted in https://github.com/TileDB-Inc/TileDB-Py/pull/2016
=> Fix deprecation and test

tiledb/cc/CMakeLists.txt, tiledb/cc/array.cc, tiledb/cc/schema.cc, tiledb/libtiledb.pxd, tiledb/tests/cc/test_cc.py
This PR defines the `TILEDB_REMOVE_DEPRECATIONS` macro, resulting in an error when deprecated core code is used.
Also removes, deprecated code.
Related PRs:
- https://github.com/TileDB-Inc/TileDB-Py/pull/2021
- https://github.com/TileDB-Inc/TileDB-Py/pull/1958
Solves:
https://github.com/jdblischak/centralized-tiledb-nightlies/issues/14
=> Define `TILEDB_REMOVE_DEPRECATIONS` macro for cc and remove deprecated code

tiledb/ctx.py, tiledb/tests/test_context_and_config.py
`__repr__` for `tiledb.Config` redacts privileged info. The values should still be accessed by directly slicing a `Config` object, but hiding them from `__repr__` reduces the risk of accidental disclosure when copy-pasting.
`unserialized_params_` used in this PR comes from https://github.com/TileDB-Inc/TileDB/blob/dev/tiledb/sm/config/config.cc#L522-L541
---
[sc-50665]
=> Hide sensitive params shown in `Config::__repr__`

setup.py
In https://github.com/TileDB-Inc/TileDB-Py/pull/2023, `TILEDB_REMOVE_DEPRECATIONS` macro was defined.
It would be good to also have this functionality in `setup.py`.
Right now, the default behavior is to remove deprecations when build TileDB-Py. In core, the default is to enable them.
Should we keep the logic, or follow the core's?
=> Expose `setup.py` flag to enable deprecations

pyproject.toml
This PR should fix issue: https://github.com/TileDB-Inc/TileDB-Py/issues/2031
I am not sure why the automated tests did not pick up on this missing dependency.
=> Add packaging as dependency

tiledb/libtiledb.pxd
Fix for failing daily tests: https://github.com/TileDB-Inc/TileDB-Py/actions/runs/10242931834
`
/home/runner/work/TileDB-Py/TileDB-Py/tiledb/schema_evolution.cc:104:14: error: ‘tiledb_current_domain_t’ was not declared in this scope; did you mean ‘tiledb_domain_t’?
`
`tiledb_current_domain_t` is needed after `CurrentDomain` wrapping: https://github.com/TileDB-Inc/TileDB-Py/pull/2015
Closes https://github.com/TileDB-Inc/TileDB-Py/issues/1986
=> Add `tiledb_current_domain_t` as type

tiledb/query_condition.py
Python's Operator Precedence Table from highest to lowest is
1. **Parentheses**: `()`
2. **Unary operators**: `+`, `-`, `~`
3. **Exponentiation**: `**`
4. **Multiplication, Division, Floor Division, Modulus**: `*`, `/`, `//`, `%`
5. **Addition and Subtraction**: `+`, `-`
6. **Bitwise Shift Operators**: `<<`, `>>`
7. **Bitwise AND**: `&`
8. **Bitwise XOR**: `^`
9. **Bitwise OR**: `|`
10. **Comparison Operators**: `==`, `!=`, `<`, `<=`, `>`, `>=`
11. **Logical NOT**: `not`
12. **Logical AND**: `and`
13. **Logical OR**: `or`
14. **Conditional Expressions**: `if - else`
15. **Lambda Expressions**: `lambda`
However, in our BNF in the docs, we have bitwise and logic operators as equal precedence which is not correct.
---
[sc-51316]
=> Get rid all BNF lines in `QueryCondition` docstring

tiledb/libtiledb.pyx
For an unknown reason, `numpy.ma.fix_invalid` behaves differently between NumPy 2.1.0 and NumPy 2.0.0. Specifically, when passing a pandas Series containing a `numpy.nan` value, `numpy.ma.fix_invalid` now makes changes in-place, even if the `copy` argument is set to its default value of `True`. This issue occurs only with pandas Series, not with NumPy arrays, for example.
Nevertheless, we don't actually need the `numpy.ma.fix_invalid` function since we handle `NaNs` later using `numpy.nan_to_num`. It would be wiser (and likely more performant) to use `numpy.ma.masked_invalid`, which simply creates a `MaskedArray` instance and allows us to obtain the mask from there.
cc: @jdblischak 
Closes https://github.com/TileDB-Inc/TileDB-Py/issues/2040
---
```
>>> import pandas as pd, numpy as np
>>> …
```
=> Fix `numpy.ma.fix_invalid` issue in NumPy 2.1.0 by replacing with `numpy.ma.masked_invalid`

tiledb/query_condition.py, tiledb/tests/test_query_condition.py
Following https://github.com/single-cell-data/TileDB-SOMA/pull/2830, https://github.com/single-cell-data/TileDB-SOMA/pull/2831, and https://github.com/single-cell-data/TileDB-SOMA/pull/2864 this PR improves some `QueryCondition` error messages.
In short, it improves error messages:
- when targeted attribute contains `.`
- on non-constant query-condition RHS
- for invalid operators in query-condition parser
---
[sc-52811]
[sc-52812]
[sc-52813]
=> Improve Query Condition error messages to align with TileDB-SOMA-Py

tiledb/libtiledb.pyx, tiledb/tests/test_dimension_label.py
=> Fix exception when calling `label_index` on a Query object

pyproject.toml, tiledb/tests/test_dask.py
Windows skipping is not needed for Dask tests. The reason behind this could be just installing `dask` and not `dask[distributed]`.
---
[sc-49892]
=> Remove Dask test skips and add Dask as a test dependency

tiledb/dataframe_.py, tiledb/tests/test_pandas_dataframe.py
Historically, `from_pandas` did not consider the `column_types` argument for index columns, only for regular columns. This PR resolves that issue.
---
[sc-19316]
=> Make `from_pandas` respect `column_types` for index dimensions

tiledb/__init__.py, tiledb/filestore.py, tiledb/fragment.py, tiledb/libtiledb.pyx, tiledb/multirange_indexing.py, tiledb/query_condition.py, tiledb/tests/test_filestore.py, tiledb/tests/test_pandas_dataframe.py, tiledb/tests/test_query_condition.py, tiledb/vfs.py
This PR removes some easy-to-delete deprecations. They come from either the TileDB-Py version or the Python version.
=> Remove deprecations

pyproject.toml, setup.py, tiledb/CMakeLists.txt, tiledb/cc/CMakeLists.txt, tiledb/tests/test_serialization.py
A problem identified even before `scikit-build-core` was introduced was that the serialization test was always skipped, even after setting it using the old/deprecated way: `python setup.py -DTILEDB_SERIALIZATION=ON`.
Additionally, elements like `tiledb.main.test_serialization.create_serialized_test_query` or `tiledb.main.TILEDB_CAPNP` were also undefined.
It turns out that the way the `test_serialization` import was handled was incorrect:
```
>>> import tiledb.main.test_serialization
ModuleNotFoundError: No module named 'tiledb.main.test_serialization'; 'tiledb.main' is not a package
```
but we were silently receiving only the `Serialization not enabled.` message
Here is the correct way:
```
>>> from tiledb.main import …
```
=> Fix serialization test and add command line option

tiledb/tests/test_pandas_dataframe.py
The tests added in #2046 were also checking the initial dtype of the columns as provided by `from_pandas`. However, since this depends on the system, Python, or NumPy (as evidenced by daily test failures), it turns out that this is not a good idea. Let's instead only check the dtypes enforced by the `column_types` argument.
Fixes https://github.com/TileDB-Inc/TileDB-Py/issues/2054
=> Don't check `dtype` if `column_types` is not set - `from_pandas`

tiledb/vfs.py
Enable passing config values with non-string types, for example:
```python
config = {"vfs.s3.no_sign_request": True}
vfs = tiledb.VFS(config=config)
```
which currently generates this error:
```
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
1. tiledb.cc.Config(arg0: tiledb.cc.Config)
2. tiledb.cc.Config()
3. tiledb.cc.Config(arg0: dict[str, str])
4. tiledb.cc.Config(arg0: str)
Invoked with: {'vfs.s3.no_sign_request': True}
```
=> Convert config values to strings in VFS init

tiledb/cc/attribute.cc, tiledb/cc/domain.cc, tiledb/cc/filter.cc, tiledb/cc/schema.cc
After https://github.com/TileDB-Inc/TileDB-Py/commit/ce8310e60a493be0fc412c92a8fb937575385649 `operator<<` is used instead of `dump` functions. Since this is introduced in `2.26.0`, building against older libtiledb versions results in failing tests: https://github.com/TileDB-Inc/TileDB-Py/actions/runs/10824513851
Daily tests workflow: https://github.com/TileDB-Inc/TileDB-Py/actions/runs/10832807692
Fixes: https://github.com/TileDB-Inc/TileDB-Py/issues/2061
=> Make dump calls conditional to fix errors when building against <2.26

tiledb/core.cc, tiledb/tests/test_util.py
Following the changes in https://github.com/TileDB-Inc/TileDB-Py/pull/2049, `object_type` now returns the string `'None'` instead of the `<class 'NoneType'>` object. This PR fixes the issue and adds a new test for this case.
The output of the new test with the old `object_type` method:
```
=========================================================================== test session starts ============================================================================
platform darwin -- Python 3.11.9, pytest-8.3.1, pluggy-1.5.0
rootdir: /Users/agis/TileDB_workspace/TileDB-Py
configfile: pyproject.toml
plugins: hypothesis-6.108.4
collected 6 items / 5 deselected / 1 selected …
```
=> Fix the `object_type` return value for the `None` case

.github/workflows/build-wheels.yml, .github/workflows/ci.yml, .github/workflows/daily-test-build-numpy.yml, .readthedocs.yml, pyproject.toml
This PR removes support for TileDB-Py on Python 3.8. Some reasons are:
- Python 3.8 reaches end-of-life in October 2024: https://devguide.python.org/versions/#supported-versions
- Continuing support for Python 3.8 has become untenable because NumPy [no longer supports it](https://pypi.org/project/numpy/1.26.4/#files)
- Reducing the number of wheels will decrease overall maintenance costs
---
[sc-48532]
=> Drop Python 3.8 support

tiledb/tests/test_cloud.py
This PR makes the skip-if condition for `test_save_and_open_array_from_cloud` stricter by requiring both a CI environment and each environment variable that it utilizes.
cc @jdblischak
=> Fix skipif condition for `test_save_and_open_array_from_cloud`

.github/workflows/ci-tiledb-from-source.yml, .github/workflows/ci_tiledb_from_source.yml
There are several PRs that we need to test against a branch of libtiledb, most commonly the `dev` branch, as they implement features/fixes we want to test before the release of the libtiledb binaries.
This PR implements a workflow to test against the TileDB core library built from source using a custom version.
---
[sc-57260]
=> Add CI to test against the TileDB core library built from source with a custom version

tiledb/tests/test_enumeration.py
=> Make error message for non-existing `Enumeration` in test conditional

tiledb/tests/test_fixes.py
Following https://github.com/TileDB-Inc/TileDB/pull/5317, the default value of `vfs.s3.region` has been changed to empty. This change allows AWS to select the default region from sources such as environment variables, profile configuration, and instance metadata.
This PR modifies some assertions that check the default value of `vfs.s3.region` when related environment variables are present.
cc @jdblischak
=> Make default value for `vfs.s3.region` in test conditional

tiledb/tests/test_fixes.py, tiledb/tests/test_libtiledb.py
Following https://github.com/TileDB-Inc/TileDB/pull/5297, this PR removes the deprecated `StorageManager` word when accessing stats dump.
cc @jdblischak
=> Handle removal of 'StorageManager' from stats dumps in 2.27

tiledb/cc/common.cc, tiledb/cc/group.cc, tiledb/group.py, tiledb/tests/cc/test_group.py, tiledb/tests/test_group.py
Even though the `GroupMetadata` and `Metadata` (used by the `Array` class) classes  utilize the same underlying code (similar C++ APIs), it was found that `GroupMetadata` does not support NumPy arrays and also lacks tests for handling such data.
This PR extends the functionality of `GroupMetadata` to handle the same data as `Metadata` and includes tests for the changes.
The modifications were made so that `GroupMetadata` uses only pybind11 and Python, without any Cython. In a future follow-up PR, the Cython `Metadata` class will be removed, and `GroupMetadata` will be renamed to `Metadata`. Additionally, the pybind11 code will be moved to a separate `metadata.cc` file. The new class will be shared across Array and Group classes.
---
[sc-57551]
=> Extend the `GroupMetadata` functionality to support NumPy arrays

CMakeLists.txt, HISTORY.md
Release branches were needed for `0.32.2` and `0.32.3`. This led to two missing commits on the `dev` branch. These commits have been cherry-picked in this PR's branch.
=> Update HISTORY for 0.32.2 and 0.32.3

tiledb/tests/test_libtiledb.py
Forgot about this in https://github.com/TileDB-Inc/TileDB-Py/pull/2088.
cc @jdblischak
=> Handle removal of 'StorageManager' from stats dumps in 2.27 - Part 2

tiledb/tests/test_enumeration.py
Unless I missed some testing done on earlier core versions I think we can just remove the version check here since TileDB `dev` has corrected the error message and it will not be present in 2.27.
For context, I had changed this message in [TileDB-Inc/TileDB#5291](https://github.com/TileDB-Inc/TileDB/pull/5291/files#diff-74ce8c89d5884c4961474244d6263b78237ca72ec9e61c9a8268b4fab73b0b53R814-R816) by adding a check earlier in the code with a different message. We essentially decided to revert those changes to fix a performance regression in [TileDB-Inc/TileDB#5349](https://github.com/TileDB-Inc/TileDB/pull/5349/files#diff-74ce8c89d5884c4961474244d6263b78237ca72ec9e61c9a8268b4fab73b0b53L812-L818) so the exception message returned to the previous format.
=> Update enumerations exception message.

.github/workflows/ci.yml
TileDB-Inc/TileDB-Py#2082 might have fixed the initial issue, but it causes PRs that we want to merge into non-dev branches to not run CI at all. For example: https://github.com/TileDB-Inc/TileDB-Py/pull/2099.
If there is no other solution, we should revert.
=> Revert "Do not run CI in PR twice"

tiledb/cc/group.cc, tiledb/group.py, tiledb/tests/test_group.py
The changes in https://github.com/TileDB-Inc/TileDB-Py/pull/2085 broke backwards compatibility for `GroupMetadata`. This PR fixes that issue. To prevent similar issues in the future, a test that reads a `Group` written with TileDB-Py 0.32.3 and verifies that all metadata values and types are as expected has been added.
Additionally, a test has been added to demonstrate the new types, following the supported types of `Array` metadata.
Temporary wheels: https://github.com/TileDB-Inc/TileDB-Py/actions/runs/11525100400
cc. @jparismorgan
=> Fix `GroupMetadata` backwards compatibility

HISTORY.md
Updates HISTORY.md for 0.32.5 and also 0.32.4 which was inadvertently released against TileDB [2.26.1](https://github.com/TileDB-Inc/TileDB/releases/tag/2.26.1).
=> Update HISTORY for 0.32.5 against TileDB 2.26.2 and 0.32.4

tiledb/core.cc, tiledb/stats.py, tiledb/tests/test_fixes.py, tiledb/tests/test_stats.py
Calling `tiledb.stats_dump(print_out=False, json=True)` returns Python dict instead of JSON string (as expected).
This PR fixes it, ensuring that
```
res = tiledb.stats_dump(print_out=False, json=True)
json.loads(res)
```
works as normal.
Additionally, it ensures that a user-friendly error is raised when `stats_enable` is not called before `stats_dump`.
---
[sc-58286]
=> Fix `stats_dump` broken return value type

.github/workflows/build-wheels.yml, .github/workflows/ci.yml, .github/workflows/daily-test-build-numpy.yml, pyproject.toml
Since October 2024, Python 3.13 has been in "bugfix" mode (also known as "maintenance" or "stable" mode): https://devguide.python.org/versions/#supported-versions.
To add support for TileDB-Py, an upgrade to the latest version of `cibuildwheel` was required, as it supports Python 3.13 and CPython 3.13. (More info: https://github.com/pypa/cibuildwheel/releases)
Testing:
- Wheels workflow: https://github.com/TileDB-Inc/TileDB-Py/actions/runs/11796573304
- Tested locally (manylinux_x86_64) on a fresh conda env with Python 3.13 and works fine!
---
[sc-57688]
=> Enable Python 3.13

tiledb/tests/test_schema_evolution.py
Following https://github.com/TileDB-Inc/TileDB/pull/5321 and https://github.com/TileDB-Inc/TileDB/pull/5362, let's add a TileDB-Py test.
---
[sc-57039]
=> Add test for dropping a fixed attribute and adding it back as var-sized

tiledb/array_schema.py, tiledb/cc/current_domain.cc, tiledb/current_domain.py, tiledb/ndrectangle.py
In https://github.com/TileDB-Inc/TileDB-Py/pull/2015, `CurrentDomain` and `NDRectangle` were wrapped using pybind11. In that PR, a workaround was introduced that involved storing a reference to the underlying `Domain` object to determine the dtype of the dimension of interest (commit of interest: https://github.com/TileDB-Inc/TileDB-Py/pull/2015/commits/63fb4baeb8d36603ce24602f7ba82d416d0e239d).
This PR takes advantage of https://github.com/TileDB-Inc/TileDB/pull/5229 to remove the workaround, thus making the code cleaner at both the Python and pybind11 levels, and reducing the complexity of the Python API.
=> Remove workaround from `CurrentDomain`/`NDRectangle`

pyproject.toml
Following https://github.com/TileDB-Inc/conda-forge-nightly-controller/pull/152, it was decided that nightlies should be the place where we check for deprecations. The goal is to eliminate the use of deprecations over time. To enhance the user experience, TileDB-Py will make use of deprecated functions when necessary until their usage is replaced.
=> Change default value of `TILEDB_REMOVE_DEPRECATIONS` to `OFF`

tiledb/ctx.py, tiledb/tests/conftest.py, tiledb/tests/test_context_and_config.py, tiledb/tests/test_vfs.py, tiledb/vfs.py
Also removes unnecessary `PatchedConfig` and `PatchedCtx`.
---
[sc-55042]
=> Implement serialization functionality for `Config` and `VFS` objects

tiledb/fragment.py
Closes https://github.com/TileDB-Inc/TileDB-Py/issues/2113
=> Fix TypeError: 'FragmentsInfoIterator' object is not iterable

tiledb/tests/cc/test_group.py, tiledb/tests/test_fixes.py, tiledb/tests/test_group.py, tiledb/tests/test_libtiledb.py, tiledb/tests/test_metadata.py
In https://github.com/TileDB-Inc/TileDB-Py/pull/1953, some tests were modified to ensure that https://github.com/TileDB-Inc/TileDB/pull/4800 worked as intended. Previously, the `timestamp` argument was occasionally used for writes to avoid failures when writes occurred *almost* concurrently. Following that change, some tests were made temporarily conditional for error identification purposes. Over the subsequent eight months, no related test failures have remained unresolved. The only directly connected issue identified and solved during this time is https://github.com/TileDB-Inc/TileDB-Py/pull/2090.
This PR removes the use of the `timestamp` argument where it was employed in a hacky manner and eliminates the use of `time.sleep`. However, not all parameterization introduced in …
=> Eliminate hacky use of timestamps and `time.sleep` in tests

.github/workflows/daily-tests.yml, CMakeLists.txt, HISTORY.md
Update HISTORY for 0.33.0 against TileDB 2.27.0
=> Update HISTORY for 0.33.0 against TileDB 2.27.0

HISTORY.md
Update HISTORY for 0.33.1 against TileDB 2.27.0
=> Update HISTORY for 0.33.1 against TileDB 2.27.0

.github/workflows/ci-tiledb-from-source.yml, .github/workflows/ci.yml, .github/workflows/daily-test-build-numpy.yml, .github/workflows/daily-test-build.yml, CONTRIBUTING.md, README.md, tiledb/tests/perf/asv.conf.json
This PR updates all references to the `dev` branch, changing them to `main`. After merging, the `dev` branch should be renamed to `main`.
This is a follow-up to https://github.com/TileDB-Inc/TileDB/pull/5407, which makes the same change for that repository.
cc. @dudoslav
=> Update references after renaming `dev` branch to `main`

tiledb/tests/test_schema_evolution.py
In https://github.com/TileDB-Inc/TileDB-Py/pull/2083, the `"S"` dtype is used in the new test to verify that dropping a fixed-size attribute and adding it back as variable-size now works as expected. However, this caused the issue described here: [https://github.com/TileDB-Inc/conda-forge-nightly-controller/issues/151#issuecomment-2507587087](https://github.com/TileDB-Inc/conda-forge-nightly-controller/issues/151#issuecomment-2507587087). 
Instead of testing with a specific value, we should test with both `"S"` and `"U"` dtypes but assert the fill value of the attribute before writing any data to it. This approach makes the test more generic for all types.
The same problem also appears in https://github.com/TileDB-Inc/TileDB-Py/pull/2114, so it would be better to apply this fix before …
=> Fix/Generalize test added in #2083

tiledb/array.py
`QueryExperimental::set_data_buffer` requires an unsigned integer as its last argument. It seems that with numpy versions earlier than 2, this argument becomes a numpy float64 (with `buffer_sizes[i]` being a numpy uint64 and `ncells` being a Python int).
Let's fix it by explicitly cast to numpy uint64.
Closes https://github.com/TileDB-Inc/TileDB-Py/issues/2127, closes https://github.com/TileDB-Inc/TileDB-Py/issues/2124.
=> Explicitly set the numpy type passed in `QueryExperimental::set_data_buffer`

.github/workflows/daily-test-build-numpy.yml, .github/workflows/daily-tests.yml
Daily tests, and specifically `daily-test-build-numpy.yml`, are a way to test TileDB-Py against different versions of numpy. Historically, the workflow checks TileDB-Py with the oldest and newest supported numpy versions.
It turns out that the logic is not working as intended. As shown in the latest scheduled workflow, it appears that `ci3`, which uses `daily-test-build-numpy.yml`, only runs once for each Python version and operating system combination. There is no numpy dimension. This was discovered after https://github.com/TileDB-Inc/TileDB-Py/issues/2127, which could have been prevented.
It seems we have used the configuration expansion described here: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-expanding-configurations. In practice, …
=> Fix the logic of daily tests to ensure both variations of numpy are run

tiledb/tests/test_libtiledb.py
(fix local failure on macos-arm64)
This is a very crude memory cleanup test which runs queries in a loop, and compares the starting and ending RSS to catch large leaks.
It fails at the current 2x ratio on macos-arm64. Increase the ratio to 2.5.
To confirm that this is not masking an arch-specific leak, I ran 10x iterations of the target function.
- `final / initial` RSS for 100 runs (current default) vs 1000 runs (local modification) in the `use_many_buffers` loop:
```
(Pdb) 1029292032 / 431456256
2.3856231487810433
(Pdb) p 1023819776 / 427802624
2.393205928535866
```
=> Increase test_memory_cleanup target ratio

tiledb/tests/test_query_condition.py
`test_qc_enumeration` has been observed to [fail](https://github.com/TileDB-Inc/TileDB-Py/actions/runs/12718853000/job/35458017629#step:12:1147) randomly. The data of the Array in that test is random, and its domain is relatively small; `(1, 100)`. As seen in the logs, this results in the `result` array containing only fill values, indicating that the condition is too strict for the Array we have. Increasing the size of the Array should resolve the issue permanently.
=> Increase the data size to avoid random failures in `test_qc_enumeration`

tiledb/array.py
This PR fixes the case when `tiledb-cloud` package is present but instances of Dense and Sparse Array are returned without the correct inheritance from: https://github.com/TileDB-Inc/TileDB-Py/blob/e1f57bd940731460d8cfbcdb74a1f763aef521c9/tiledb/array.py#L425-L431.
---
[sc-61938]
=> Bugfix: Arrays losing CloudArray interface

tiledb/dataframe_.py, tiledb/tests/test_pandas_dataframe.py
This PR adds support for specifying `"blob"` as a pseudo-dtype in `from_pandas`, like we do for numpy dtypes.
---
[sc-37127]
=> Add support for `BLOB` attribute type override in `from_pandas`

tiledb/dense_array.py, tiledb/sparse_array.py, tiledb/tests/test_libtiledb.py
This PR fixes an issue where the `attr` argument in the `Array.open` method (internally stored as `view_attr`) was not respected during query operations. Consequently, the `Array.query` method ignored the specified attribute(s) and returned all attributes instead. The issue has been resolved by updating the `__getitem__` and `subarray` methods of both Sparse and Dense Arrays.
---
[sc-61659]
=> Fix `view_attr` not being respected by `__getitem__` and `subarray`

tiledb/npbuffer.cc, tiledb/tests/test_fixes.py
This PR fixes an issue with the incorrect calculation of the `data_buffer` size when empty bytes are present in the Python list being written to a TileDB Array. The size of the `data_buffer` was incorrectly set to the size of the Python list, which is incorrect because empty bytes are not included in the `data_buffer` being sent to the `QueryExperimental::set_data_buffer` C++ API.
---
[sc-62594]
=> Bug fix: Data buffer is not resized for byte objects after completing the buffer and offsets conversion

.github/workflows/ci.yml, tiledb/tests/test_timestamp_overrides.py
This PR fixes the issue we are experiencing with macOS 13 runners when running tests that require faketime. Let's disable faketime tests on macOS.
Log: https://gist.github.com/kounelisagis/d88c23c65e1198556f0493e45c357e4c
---
[sc-63017]
=> Skip faketime tests on macOS

tiledb/array_schema.py
I noticed the HTML generated after using the `.schema` property on an open array was incorrect and missing a closing tag.
=> Fix bug with printing array schemas to HTML

tiledb/array.py, tiledb/multirange_indexing.py, tiledb/tests/test_fixes.py
After introducing Current Domain in https://github.com/TileDB-Inc/TileDB-Py/pull/2015, there is still work to be done to fully utilize it. This PR addresses cases where the domain was used without considering the Current Domain.
The original issue arose from the following TileDB-SOMA example, where using the full domain of the array eventually led to an OOM crash:
```
import tiledb, tiledbsoma as soma
import numpy as np
import pyarrow as pa
A = soma.DenseNDArray.create("foo",type=pa.int8(),shape=(10,5))
A.write((slice(None),slice(None)), pa.Tensor.from_numpy(np.arange(0, 50).reshape(10,5)))
A.close()
A = tiledb.open("foo", mode="r")
A.query().df[:]
```
---
[sc-61914]
=> Consider the Current Domain on indexing

tiledb/libtiledb/current_domain.cc, tiledb/tests/test_current_domain.py
This PR addresses an issue where the `NDRectangle::set_range` overloads were ignored, and only the first overload (`uint64_t`) was used after casting the arguments to `uint64_t`. The `NDRectangle::range_dtype` is now utilized to determine the appropriate type (`T`) to use.
=> Fix `NDRectangle::set_range` overloads

.github/workflows/build-wheels.yml, pyproject.toml, tiledb/tests/test_dask.py
This PR introduces the `@pytest.mark.flaky` decorator to retry `test_dask_multiattr_2d` up to 3 times with a 2-second delay between attempts. This helps mitigate intermittent test failures caused by factors such as network instability, timeouts, or race conditions.
Fixes https://github.com/TileDB-Inc/TileDB-Py/issues/2149
=> Add pytest flaky-retry mechanism for handling intermittent test failures

tiledb/npbuffer.cc, tiledb/tests/common.py, tiledb/tests/test_libtiledb.py
This PR expands `test_sparse_string_domain` for empty strings.
=> Expand `test_sparse_string_domain` for empty strings

tiledb/tests/strategies.py, tiledb/tests/test_multi_index-hp.py
The test `TestMultiIndexPropertySparse.test_multi_index_two_way_query` has been frequently failing due to `hypothesis.errors.FailedHealthCheck`, with error messages such as:
`It looks like your strategy is filtering out a lot of data. The health check found 50 filtered examples but only 9 valid ones.`
This PR changes `ranges` strategy to prevent Hypothesis health check failures caused by excessive test case filtering while still ensuring coverage of all valid ranges.
=> Fix `test_multi_index_two_way_query` FailedHealthCheck

tiledb/tests/test_current_domain.py, tiledb/tests/test_dask.py
We currently have two failing tests:
- `test_take_current_domain_into_account_sparse_indexing_sc61914` - Changed to our own assertion function since using `pd.DataFrame.equals` was resulting in an error for windows with numpy 1 even though the Dataframes were equal.
More: https://github.com/TileDB-Inc/TileDB-Py/issues/2161
- `test_dask_multiattr_2d` - used `rerun_except="TileDBError"` instead of needing to import error types from two different packages. This was leading to `ModuleNotFoundError: No module named 'distributed'` for Windows platforms. This was maybe caused by missing test dependencies, but we can avoid that.
More: https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=41877&view=logs&j=ea6b747a-d678-5a49-8233-1092783ec463&t=1da0fa6e-ac3c-538d-9479-a05b27431549&l=1694 …
=> Fix failing tests

tiledb/array.py, tiledb/libtiledb/array.cc, tiledb/tests/test_libtiledb.py
As discovered in [TileDB-ML](https://github.com/TileDB-Inc/TileDB-ML/actions/runs/13406770379/job/37448019451#step:8:35492), calling the `Array::_non_empty_domain` pybind11 function on a `TILEDB_ASCII` dimension containing non-decodable bytes (in terms of UTF-8) resulted in errors such as:  
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 0: invalid start byte`.  
The `pybind11::make_tuple` function assumed that the input would always be a printable string, requiring special handling for this case.  
This PR addresses the issue and also ensures that an exception is thrown for dimensions of unicode string type, as this is not supported until TileDB 2.27.0.
=> Fix the error caused by non-decodable bytes when retrieving the non-empty domain for `TILEDB_ASCII` dimensions

tiledb/tests/test_multi_index-hp.py
This test regularly fails on linux-64 tiledb-py-feedstocks builds (https://github.com/TileDB-Inc/conda-forge-nightly-controller/issues/167, https://github.com/TileDB-Inc/conda-forge-nightly-controller/issues/170, https://github.com/conda-forge/tiledb-py-feedstock/pull/256), but we have been unable to reproduce it elsewhere (even when using `build-locally.py` to locally mimic the conda-forge feedstock setup in a Docker container).
This PR skips the problematic test when the env var `CONDA_BUILD` is set to `1` (set by [conda-build](https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html)). I tested this branch in my [feedstock fork](https://github.com/jdblischak/tiledb-py-feedstock/commit/55ba65ada03a75165ba1bb61132528d94c8679a6) to confirm the flaky test …
=> Skip test that randomly fails on linux-64 tiledb-py-feedstock Azure builds

tiledb/multirange_indexing.py, tiledb/npbuffer.cc, tiledb/tests/test_attribute.py, tiledb/tests/test_pandas_dataframe.py
This PR adds tests with heterogeneous arrays that contain variable-length nullable numeric attributes. Additionally, it provides an appropriate error message when `Arrow` is used in such cases. The new message replaces the misleading `Expected 2 buffers for imported type uint32, ArrowArray struct has 3` error that was previously displayed.
In a future PR, support for Arrow could be added once this is supported by Arrow C Data Interface.
---
[sc-41582]
=> Add tests with heterogeneous arrays that contain variable-length nullable numeric attributes

.github/workflows/daily-tests.yml
TileDB [2.26.3](https://github.com/TileDB-Inc/TileDB/releases/tag/2.26.3) is a build system-only update release. As a result, no artifacts are present, causing daily tests that check for backward compatibility to fail. This PR pins the version to [2.26.2](https://github.com/TileDB-Inc/TileDB/releases/tag/2.26.2).
Fixes #2163
=> Pin TileDB 2.26.2 to prevent backward compatibility daily test failures

tiledb/array.py, tiledb/array_schema.py, tiledb/multirange_indexing.py, tiledb/tests/test_attribute.py, tiledb/tests/test_multi_index.py, tiledb/tests/test_pandas_dataframe.py
This PR expands the cases where a Pandas DataFrame can be retrieved from a TileDB `Array` or `Query`. This improvement applies _only_ when the `use_arrow` argument is not set.  
If the `pyarrow` package was available, `use_arrow` would automatically be set to `True`. This caused issues in cases involving multi-value attributes. The problem was that the user never explicitly requested Arrow, yet encountered an Arrow-related issue. Additionally, the expected `TileDBError` for multi-value attributes was never triggered because the loop `for attr in map(array.attr, query.attrs or ())` did not work as intended. The reason is that `array.attr` is a method that takes an attribute index or name as a parameter, rather than returning attributes directly.  
A new method, `attr_names`, has been …
=> Improve the logic for using `Arrow` when it is not explicitly requested

tiledb/query_condition.py, tiledb/tests/test_query_condition.py
Similarly to https://github.com/single-cell-data/TileDB-SOMA/pull/3746, let's fix the issue where a query condition contains attributes with dot(s) when using the `in` operator.
---
[sc-63843]
=> Fix for query conditions that contain attributes with dot(s) when using the `in` operator

tiledb/array.py, tiledb/multirange_indexing.py, tiledb/tests/test_pandas_dataframe.py
This PR expands the functionality of the `.df` TileDB Array/Query accessor to also allow indexing with both PyArrow and NumPy arrays, instead of only scalar, slice, or a list of scalars or slice objects, as it currently does.
cc. @johnkerl for visibility.
---
[sc-63089]
=> Expand `.df` Array/Query accessor to allow indexing with NumPy and PyArrow arrays

tiledb/stats.py, tiledb/tests/common.py, tiledb/tests/test_stats.py
This PR fixes `stats_reset()`, which was noticed to not reset stats after calling `tiledb.stats_reset()`.
---
[sc-63203]
=> Fix `stats_reset()` behavior

.github/workflows/daily-tests.yml, CMakeLists.txt, HISTORY.md
Update HISTORY for 0.33.5 against TileDB 2.27.2
=> Update HISTORY for 0.33.5 against TileDB 2.27.2

tiledb/array.py, tiledb/tests/test_libtiledb.py
`self.array.uri` would need to be changed to private method `self.array._uri()`. But the attribute is stored to the Py class so use it as is done in logic down on ln 766.
This impacts APIs including tiledb-py, cloud-py and any other API consolidating with specific fragments URIs
=> Fix URI passed to consolidation

tiledb/array.py, tiledb/multirange_indexing.py, tiledb/tests/test_current_domain.py
This PR fixes an issue originating from https://github.com/TileDB-Inc/TileDB-Py/pull/2156, which resulted in the current domain being used whenever it was present. This caused problems when indexing with an explicit `idx` while a current domain was present, leading to `idx` and nonempty domain not being used.
cc. @ypatia
---
[sc-64437]
=> Fix: Consider index passed, even if the current domain is present

tiledb/libtiledb/attribute.cc, tiledb/libtiledb/current_domain.cc, tiledb/libtiledb/dimension_label.cc, tiledb/libtiledb/enumeration.cc, tiledb/libtiledb/filter.cc, tiledb/libtiledb/schema.cc, tiledb/schema_evolution.cc, tiledb/tests/test_fixes.py
This PR links the lifetime of the constructor's `ctx` element to the constructed object of each pybind11 class. This will fix instances failing to hold a Python pointer to the provided context, which causes errors when the `ctx` object is garbage collected.
---
[sc-64885]
=> Add the missing `keep_alive` for `ctx` passed to pybind11 class constructors

tiledb/aggregation.py, tiledb/array.py, tiledb/dense_array.py, tiledb/sparse_array.py, tiledb/tests/test_pandas_dataframe.py
This PR expands the functionality of the square bracket TileDB Array accessor to allow indexing with Python lists, PyArrow arrays, and NumPy arrays (for point queries), in addition to the currently supported scalar, slice, or tuple indexing.
cc. @johnkerl for visibility.
---
[sc-64094]
=> Expand type support for built-in array indexer

tiledb/tests/test_fork_ctx.py
This PR modifies the tests in `test_fork_ctx.py` to run as subprocesses, fixing #2175. This has been verified by running the "Build and test wheels" workflow against the current branch: [run](https://github.com/TileDB-Inc/TileDB-Py/actions/runs/14227535058/job/39870535651). The failure rate was previously 100% for macos.
---
[sc-64149][sc-57975]
=> Run tests of `test_fork_ctx` as subprocesses

tiledb/tests/test_vfs.py
Following https://github.com/TileDB-Inc/TileDB/pull/5480, let's remove the code that tests non-existent VFS parent directories.
We could make the code conditional based on the TileDB Arrays version, but I would prefer not to.
Addresses a part of https://github.com/TileDB-Inc/conda-forge-nightly-controller/issues/180
cc. @jdblischak
=> Remove testing of non-existent VFS parent directories

tiledb/tests/test_libtiledb.py
Support for HDFS was removed upstream in TileDB in https://github.com/TileDB-Inc/TileDB/pull/5496. Now the nightly TileDB-Py builds against nightly TileDB fail this test with a `KeyError`.
xref: https://github.com/TileDB-Inc/conda-forge-nightly-controller/issues/182#issuecomment-2806755307, https://github.com/TileDB-Inc/centralized-tiledb-nightlies/issues/46#issuecomment-2806899886
=> Remove failing test now that HDFS support has been removed

tiledb/__init__.py
This PR prevents `CCProxy.__getattr__` from emitting deprecation warnings when accessing special attributes, such as `__file__`.
Hypothesis 6.131.1 [introduced logic that inspects local modules by accessing constant values](https://github.com/HypothesisWorks/hypothesis/releases/tag/hypothesis-python-6.131.1), including attributes like `__file__`. This triggered warnings during test runs due to our proxy class warning.
Closes #2183, closes https://github.com/TileDB-Inc/centralized-tiledb-nightlies/issues/47
cc. @jdblischak
=> Avoid deprecation warnings for special attribute access in `CCProxy` after Hypothesis 6.131.1 update

README.md, docs/building-from-source.md
These were originally in GitBook, so I'm moving them here.
=> Add Building from Source docs to TileDB-Py

tiledb/tests/test_libtiledb.py
Since TileDB version 2.28.0, `hdfs` is no longer supported. As a result, the dictionary returned by `tiledb.as_built()` does not contain the `hdfs` key.
Fixes https://github.com/TileDB-Inc/conda-forge-nightly-controller/issues/184
cc. @jdblischak
=> Fix `hdfs` KeyError for libtiledb>=2.28

.github/workflows/build-wheels.yml
Following https://github.com/TileDB-Inc/TileDB/pull/5398, TileDB-Py is affected, meaning that the manylinux images in the build wheels workflow should be updated to the [future default](https://cibuildwheel.pypa.io/en/stable/options/#linux-image), `manylinux_2_28`.
=> Set manylinux images to `manylinux_2_28` for build wheels workflow

.github/workflows/daily-tests.yml, CMakeLists.txt, HISTORY.md
Update HISTORY for 0.34.0 against TileDB 2.28.0
=> Update HISTORY for 0.34.0 against TileDB 2.28.0

.github/workflows/build-wheels.yml, pyproject.toml
In https://github.com/TileDB-Inc/TileDB-Py/pull/2162, `rerun_except="TileDBError"` was used to handle the sporadic failure of `test_dask_multiattr_2d` due to a `distributed.comm.core.CommClosedError`, which caused the error:
```
ERROR - Failed to communicate with scheduler during heartbeat.
```
However, it appears that this was not working as intended, and the test was never retried (causing daily tests to fail: https://github.com/TileDB-Inc/TileDB-Py/issues/2196). The reason for this is that I was using `pytest-rerunfailures` locally, but only `pytest-retry` was installed in CI.
`pytest-retry` appears to be significantly less maintainable and capable compared to `pytest-rerunfailures`, so switching to `pytest-rerunfailures` would be a far better choice. This change is also expected to …
=> Switch from `pytest-retry` to `pytest-rerunfailures`

tiledb/highlevel.py, tiledb/tests/test_fragments.py
This PR addresses an issue that occurred when no Config was provided by the user during array consolidation. In such cases, the consolidation parameters set in the Context were ignored because an empty Config object was implicitly created in the Python layer and passed to the C++ API, which then took precedence over the Context.
Closes CORE-288
=> Fix: respect context params during array consolidation when no config is provided

pyproject.toml
Daily tests and nightly feedstock builds have been consistently failing since the release of pybind11 3.0.0:
https://github.com/pybind/pybind11/releases/tag/v3.0.0 / https://pypi.org/project/pybind11/3.0.0/
More specifically, the daily tests fail on macOS 13 with Python 3.13, and the feedstock builds fail on Linux ppc64le with Python 3.9.
The failing test appears to be unrelated, and after some experimentation, there doesn't seem to be an easy fix. This PR constrains the pybind11 version to less than 3 to avoid these issues for now.
Daily tests workflow run on this branch: https://github.com/TileDB-Inc/TileDB-Py/actions/runs/16321135225
Support for pybind11 3.0 will be addressed in a future PR, as outlined in CORE-304.
cc. @jdblischak 
---
The failure log:
``` …
```
=> Constrain pybind11 version to less than 3

tiledb/array.py, tiledb/tests/test_libtiledb.py
Attempting to read an encrypted array by passing the `key` parameter to `array_open` wasn't propagating the `key` to the Core. This was because `preload_array` only looked for the `key` parameter when no `Context` was passed to it. Since `preload_array` is an internal function and `Context` is always passed, this PR removes the case where `Context` is not present, thereby fixing the issue.
Closes CORE-243
=> Ensure that the encryption key is propagated correctly when opening an array

tiledb/query_condition.cc, tiledb/query_condition.py, tiledb/tests/test_query_condition.py
Comparing against `None` is already supported by libtiledb for nullable attributes. This PR adds support for it in TileDB-Py.
Closes CORE-249
=> Add query condition support for comparing against `None`

CMakeLists.txt, examples/profile.py, tiledb/__init__.py, tiledb/libtiledb/CMakeLists.txt, tiledb/libtiledb/profile.cc, tiledb/libtiledb/tiledbcpp.cc, tiledb/profile.py, tiledb/tests/test_examples.py, tiledb/tests/test_profile.py
Wrapping https://github.com/TileDB-Inc/TileDB/pull/5492, https://github.com/TileDB-Inc/TileDB/pull/5498, https://github.com/TileDB-Inc/TileDB/pull/5539, https://github.com/TileDB-Inc/TileDB/pull/5547, and https://github.com/TileDB-Inc/TileDB/pull/5552.
The above PRs introduce the Profiles functionality, aimed at providing users with a seamless experience across all TileDB APIs. With Profiles, users can log in once and only once, interacting with a single source of truth across all APIs - without needing to be aware of the underlying implementation details.
On the TileDB-Py side, this is achieved by integrating Profiles into the Config via new `profile_name` and `profile_dir` Config parameters. Profiles created with the default name and directory are automatically loaded, eliminating the …
=> Wrap `Profile`

.github/workflows/daily-test-build-numpy.yml, .github/workflows/daily-test-build.yml
This is expected to resolve the "could not assign - user not found" error observed in the recent daily test failures.
=> Update assignees for nightly build workflows

tiledb/libtiledb/array.cc, tiledb/libtiledb/group.cc, tiledb/libtiledb/object.cc, tiledb/libtiledb/vfs.cc
Previously, we only released the GIL during query execution. However, C++ API calls such as `Array::open`, `ArraySchema::load`, and `Array::consolidate` could still unnecessarily block Python threads. This PR expands the scope of GIL release within the pybind11 bindings, focusing primarily on I/O-intensive operations where the impact is most significant. These improvements aim to enhance overall concurrency and responsiveness in multithreaded Python environments.
Probably closes CORE-262
=> Expand GIL release scope for improved threading support

tiledb/fragment.py
The `__lock.tdb` file was removed from the array folder in [TileDB 2.7.0](https://github.com/TileDB-Inc/TileDB/releases/tag/2.7.0). This PR removes support for handling these files.
Closes https://github.com/TileDB-Inc/centralized-tiledb-nightlies/issues/54
cc. @jdblischak
=> Remove outdated lock handling from `create_array_from_fragments`

tiledb/tests/test_query_condition.py
A frequent failure in `test_string_dense` during daily tests occurs when the generated query condition string contains a single quote (`'`). Previously, this -correctly- caused a parsing error, leading to test failures.
The PR expands the test strings by adding two cases: one with a single quote (which was failing before) and one with a double quote. The strings are now safely escaped using `repr()`.
Ref CORE-377
=> Escape quotes in query condition test strings

tiledb/core.cc, tiledb/tests/test_aggregates.py
This PR fixes overflow issues in sum aggregations by upcasting results to wider types (`int8`/`int16`/`int32` → `int64`, `uint8`/`uint16`/`uint32` → `uint64`, `float` → `double`). The results are returned correctly by the Core APIs, but at the pybind11 layer of TileDB-Py they were being cast to types that could not hold them. This PR also adds corner-case tests with extreme values to prevent regressions and ensure mathematically correct results.
=> Upcast sum aggregation results to prevent overflows

tiledb/tests/test_aggregates.py
The changes in https://github.com/TileDB-Inc/TileDB-Py/pull/2244 caused an overflow when applying `numpy.sum` on Windows runners using numpy 1 on Daily Tests last night. The result from the Core appears to be correct, and this behavior seems to have been fixed in numpy 2. To work around this issue without lots of changes, let's just switch back to Python's built-in `sum`.
Daily tests run on this branch: https://github.com/TileDB-Inc/TileDB-Py/actions/runs/17862604593
---
Closes #2240
=> Fix `numpy.sum` overflow in aggregate tests

tiledb/libtiledb/metadata.h
This PR fixes an issue introduced with the latest pybind11 release (version 3.0). Specifically, `test_cc.py::test_array` was failing in some macOS-13 jobs with the following error:
```
arr._open(lt.QueryType.WRITE)
arr._set_open_timestamp_start(2)
arr._set_open_timestamp_end(2)
arr._delete_metadata("key")
arr._close()
arr._set_open_timestamp_start(3)
arr._set_open_timestamp_end(3)
arr._open(lt.QueryType.READ)
>       with pytest.raises(KeyError):
^^^^^^^^^^^^^^^^^^^^^^^
E       Failed: DID NOT RAISE <class 'KeyError'>
```
It turns out that initializing the `uint32_t value_num`, which is passed to the `Array::get_metadata` C++ API, fixes the problem. The CI results for this branch should not be considered, since pybind11 is still pinned to <3. I would like to handle this in a separate PR. …
=> Initialize `uint32_t` to prevent OS-dependent undefined behavior
